Repository apache-superset/superset-ui, pull requests merged in 2018-12, with the labels that each got.

#46 Remove leading and trailing space when looking up formatter
  packages/superset-ui-number-format/src/NumberFormatterRegistry.js
  packages/superset-ui-number-format/test/NumberFormatterRegistry.test.js
  packages/superset-ui-time-format/src/TimeFormatterRegistry.js
  packages/superset-ui-time-format/test/TimeFormatterRegistry.test.js
Labels: #feature, reviewable

#45 Fix typo in unit test description
  packages/superset-ui-number-format/test/factories/createD3NumberFormatter.test.js
  packages/superset-ui-number-format/test/factories/createSiAtMostNDigitFormatter.test.js
  packages/superset-ui-time-format/test/factories/createMultiFormatter.test.js
Labels: #code-quality, reviewable

#51 Add reactify
  package.json
  packages/superset-ui-chart/src/components/reactify.jsx
  packages/superset-ui-chart/src/index.js
  packages/superset-ui-chart/test/components/createLoadableRenderer.test.jsx
  packages/superset-ui-chart/test/components/reactify.test.jsx
  packages/superset-ui-chart/test/index.test.js
Labels: #feature, reviewable

#52 [bugfix][connection] fix client promise
  packages/superset-ui-connection/src/SupersetClient.ts
Labels: #bug, reviewable

#53 Separate SupersetClient and SupersetClientClass
  package.json
  packages/superset-ui-connection/src/SupersetClient.ts
  packages/superset-ui-connection/src/SupersetClientClass.ts
  packages/superset-ui-connection/src/index.ts
  packages/superset-ui-connection/test/SupersetClient.test.ts
  packages/superset-ui-connection/test/SupersetClientClass.test.ts
  packages/superset-ui-connection/test/callApi/parseResponse.test.js
Labels: #code-quality, reviewable

#55 Convert chart models to TS and export additional modules
  packages/superset-ui-chart/src/index.js
  packages/superset-ui-chart/src/models/ChartMetadata.js
  packages/superset-ui-chart/src/models/ChartMetadata.ts
  packages/superset-ui-chart/src/models/ChartPlugin.js
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/src/models/ChartProps.js
  packages/superset-ui-chart/src/models/ChartProps.ts
  packages/superset-ui-chart/src/query/FormData.ts
  packages/superset-ui-chart/src/query/Metric.ts
  packages/superset-ui-chart/src/query/buildQueryContext.ts
  packages/superset-ui-chart/src/query/buildQueryObject.ts
  packages/superset-ui-chart/src/query/index.ts
  packages/superset-ui-chart/src/registries/ChartBuildQueryRegistrySingleton.ts
  packages/superset-ui-chart/src/registries/ChartComponentRegistrySingleton.ts
  packages/superset-ui-chart/src/registries/ChartMetadataRegistrySingleton.ts
  packages/superset-ui-chart/src/registries/ChartTransformPropsRegistrySingleton.ts
  packages/superset-ui-chart/test/models/ChartMetadata.test.ts
  packages/superset-ui-chart/test/models/ChartPlugin.test.ts
  packages/superset-ui-chart/test/models/ChartProps.test.ts
  packages/superset-ui-chart/test/query/buildQueryContext.test.ts
  packages/superset-ui-chart/test/query/buildQueryObject.test.ts
  packages/superset-ui-chart/types/external.d.ts
Labels: #code-quality, #feature, reviewable

#59 Make connection and color packages peer dependencies
  packages/superset-ui-chart/package.json
  packages/superset-ui-demo/package.json
Labels: #bug, reviewable

#61 Allow metrics arrays in form data
  packages/superset-ui-chart/src/query/FormData.ts
  packages/superset-ui-chart/src/query/Metric.ts
  packages/superset-ui-chart/test/query/Metric.test.ts
Labels: #feature, reviewable

#57 Add ChartClient (v2)
  packages/superset-ui-chart/package.json
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-chart/src/index.js
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/src/query/FormData.ts
  packages/superset-ui-chart/test/clients/ChartClient.test.ts
  packages/superset-ui-chart/test/index.test.js
  packages/superset-ui-chart/test/models/ChartPlugin.test.ts
  packages/superset-ui-chart/test/query/Metric.test.ts
  packages/superset-ui-chart/test/query/buildQueryContext.test.ts
  packages/superset-ui-chart/test/query/buildQueryObject.test.ts
  packages/superset-ui-connection/src/SupersetClient.ts
Labels: #feature, reviewable

#56 [build] fix typescript builds
  package.json
  packages/superset-ui-chart/package.json
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-chart/src/components/createLoadableRenderer.js
  packages/superset-ui-chart/src/components/createLoadableRenderer.ts
  packages/superset-ui-chart/src/components/reactify.jsx
  packages/superset-ui-chart/src/components/reactify.tsx
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/query/FormData.ts
  packages/superset-ui-chart/test/clients/ChartClient.test.ts
  packages/superset-ui-chart/test/components/createLoadableRenderer.test.tsx
  packages/superset-ui-chart/test/components/reactify.test.tsx
  packages/superset-ui-chart/test/models/ChartPlugin.test.ts
  packages/superset-ui-connection/src/SupersetClient.ts
  packages/superset-ui-connection/src/callApi/parseResponse.ts
  packages/superset-ui-connection/src/index.ts
  packages/superset-ui-connection/src/types.ts
  packages/superset-ui-connection/test/SupersetClientClass.test.ts
  packages/superset-ui-connection/test/callApi/callApi.test.ts
  packages/superset-ui-connection/test/callApi/parseResponse.test.ts
  packages/superset-ui-connection/test/utils/throwIfCalled.ts
  packages/superset-ui-connection/types/external.d.ts
  packages/superset-ui-time-format/test/factories/createD3TimeFormatter.test.js
Labels: #bug, #code-quality, reviewable

#62 Convert core to TS
  package.json
  packages/superset-ui-chart/test/models/ChartPlugin.test.ts
  packages/superset-ui-core/src/index.ts
  packages/superset-ui-core/src/models/ExtensibleFunction.ts
  packages/superset-ui-core/src/models/Plugin.ts
  packages/superset-ui-core/src/models/Preset.js
  packages/superset-ui-core/src/models/Preset.ts
  packages/superset-ui-core/src/models/Registry.ts
  packages/superset-ui-core/src/models/RegistryWithDefaultKey.js
  packages/superset-ui-core/src/models/RegistryWithDefaultKey.ts
  packages/superset-ui-core/src/utils/convertKeysToCamelCase.ts
  packages/superset-ui-core/src/utils/isDefined.js
  packages/superset-ui-core/src/utils/isDefined.ts
  packages/superset-ui-core/src/utils/isRequired.js
  packages/superset-ui-core/src/utils/isRequired.ts
  packages/superset-ui-core/src/utils/makeSingleton.js
  packages/superset-ui-core/src/utils/makeSingleton.ts
  packages/superset-ui-core/test/index.test.ts
  packages/superset-ui-core/test/models/ExtensibleFunction.test.js
  packages/superset-ui-core/test/models/ExtensibleFunction.test.ts
  packages/superset-ui-core/test/models/Plugin.test.ts
  packages/superset-ui-core/test/models/Preset.test.ts
  packages/superset-ui-core/test/models/Registry.test.ts
  packages/superset-ui-core/test/models/RegistryWithDefaultKey.test.ts
  packages/superset-ui-core/test/utils/convertKeysToCamelCase.test.ts
  packages/superset-ui-core/test/utils/isDefined.test.ts
  packages/superset-ui-core/test/utils/isRequired.test.ts
  packages/superset-ui-core/test/utils/makeSingleton.test.ts
Labels: #code-quality, reviewable

#68 Add SuperChart
  packages/superset-ui-chart/src/components/SuperChart.tsx
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/models/ChartMetadata.ts
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/src/models/ChartProps.ts
  packages/superset-ui-chart/test/components/SuperChart.test.jsx
  packages/superset-ui-chart/test/components/SuperChart.test.tsx
  packages/superset-ui-chart/test/models/ChartMetadata.test.ts
  packages/superset-ui-chart/test/models/ChartProps.test.ts
Labels: #feature, reviewable
