Repository apache-superset/superset-ui, pull requests merged in 2019-08, with the labels that each got.

#200 feat: allow reactify callbacks to access props
  packages/superset-ui-chart/src/components/reactify.tsx
Labels: size/XS

#199 feat: optimize functions for getting text dimension
  packages/superset-ui-dimension/src/getMultipleTextDimensions.ts
  packages/superset-ui-dimension/src/getTextDimension.ts
  packages/superset-ui-dimension/src/index.ts
  packages/superset-ui-dimension/src/svg/LazyFactory.ts
  packages/superset-ui-dimension/src/svg/constants.ts
  packages/superset-ui-dimension/src/svg/createHiddenSvgNode.ts
  packages/superset-ui-dimension/src/svg/createTextNode.ts
  packages/superset-ui-dimension/src/svg/factories.ts
  packages/superset-ui-dimension/src/svg/getBBoxCeil.ts
  packages/superset-ui-dimension/src/svg/updateTextNode.ts
  packages/superset-ui-dimension/test/computeMaxFontSize.test.ts
  packages/superset-ui-dimension/test/getBBoxDummyFill.ts
  packages/superset-ui-dimension/test/getMultipleTextDimensions.test.ts
  packages/superset-ui-dimension/test/getTextDimension.test.ts
  packages/superset-ui-dimension/test/svg/LazyFactory.test.ts
  packages/superset-ui-dimension/test/svg/getBBoxCeil.test.ts
  packages/superset-ui-dimension/test/svg/updateTextNode.test.ts
Labels: reviewable, size/XL

#178 feat: split superset-ui/query from superset-ui/chart
  packages/superset-ui-chart/package.json
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-chart/src/components/ChartDataProvider.tsx
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/src/registries/ChartBuildQueryRegistrySingleton.ts
  packages/superset-ui-chart/src/types/TransformFunction.ts
  packages/superset-ui-chart/test/clients/ChartClient.test.ts
  packages/superset-ui-chart/test/components/MockChartPlugins.tsx
  packages/superset-ui-chart/test/models/ChartPlugin.test.tsx
  packages/superset-ui-query/README.md
  packages/superset-ui-query/package.json
  packages/superset-ui-query/src/DatasourceKey.ts
  packages/superset-ui-query/src/buildQueryContext.ts
  packages/superset-ui-query/src/buildQueryObject.ts
  packages/superset-ui-query/src/convertFilter.ts
  packages/superset-ui-query/src/convertMetric.ts
  packages/superset-ui-query/src/index.ts
  packages/superset-ui-query/src/processExtras.ts
  packages/superset-ui-query/src/processFilters.ts
  packages/superset-ui-query/src/processMetrics.ts
  packages/superset-ui-query/src/types/Column.ts
  packages/superset-ui-query/src/types/Datasource.ts
  packages/superset-ui-query/src/types/Filter.ts
  packages/superset-ui-query/src/types/Metric.ts
  packages/superset-ui-query/src/types/Operator.ts
  packages/superset-ui-query/src/types/Query.ts
  packages/superset-ui-query/src/types/QueryFormData.ts
  packages/superset-ui-query/src/types/Time.ts
  packages/superset-ui-query/test/DatasourceKey.test.ts
  packages/superset-ui-query/test/buildQueryContext.test.ts
  packages/superset-ui-query/test/buildQueryObject.test.ts
  packages/superset-ui-query/test/convertFilter.test.ts
  packages/superset-ui-query/test/convertMetric.test.ts
  packages/superset-ui-query/test/processFilters.test.ts
  packages/superset-ui-query/test/processMetrics.test.ts
  packages/superset-ui-query/test/types/Filter.test.ts
Labels: #code-quality, reviewable

#202 feat: deprecate old SuperChart API that accepts chartProps
  packages/superset-ui-chart/src/components/SuperChartShell.tsx
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/test/components/SuperChart.test.tsx
Labels: reviewable, size/L

#203 feat: include control panel in the chart plugin
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/models/ChartControlPanel.ts
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/src/registries/ChartControlPanelRegistrySingleton.ts
  packages/superset-ui-chart/test/index.test.js
  packages/superset-ui-chart/test/models/ChartPlugin.test.tsx
Labels: reviewable, size/M

#201 feat: Add types and type guards for encodeable
  packages/superset-ui-encodeable/README.md
  packages/superset-ui-encodeable/package.json
  packages/superset-ui-encodeable/src/index.ts
  packages/superset-ui-encodeable/src/typeGuards/Base.ts
  packages/superset-ui-encodeable/src/typeGuards/ChannelDef.ts
  packages/superset-ui-encodeable/src/types/Axis.ts
  packages/superset-ui-encodeable/src/types/Base.ts
  packages/superset-ui-encodeable/src/types/Channel.ts
  packages/superset-ui-encodeable/src/types/ChannelDef.ts
  packages/superset-ui-encodeable/src/types/Data.ts
  packages/superset-ui-encodeable/src/types/Legend.ts
  packages/superset-ui-encodeable/src/types/Scale.ts
  packages/superset-ui-encodeable/src/types/VegaLite.ts
  packages/superset-ui-encodeable/src/utils/identity.ts
  packages/superset-ui-encodeable/src/utils/isDisabled.ts
  packages/superset-ui-encodeable/src/utils/isEnabled.ts
  packages/superset-ui-encodeable/test/typeGuards/Base.test.ts
  packages/superset-ui-encodeable/test/typeGuards/ChannelDef.test.ts
  packages/superset-ui-encodeable/test/utils/identity.test.ts
  packages/superset-ui-encodeable/test/utils/isDisabled.test.ts
  packages/superset-ui-encodeable/test/utils/isEnabled.test.ts
Labels: reviewable, size/L

#174 refactor(chart): remove and rename fields in ChartProps
  packages/superset-ui-chart/src/models/ChartProps.ts
  packages/superset-ui-chart/test/components/SuperChartCore.test.tsx
  packages/superset-ui-chart/test/models/ChartProps.test.ts
Labels: reviewable, size/L

#205 feat: add functions for parsing formatters from encoding
  packages/superset-ui-encodeable/package.json
  packages/superset-ui-encodeable/src/parsers/createFormatterFromChannelDef.ts
  packages/superset-ui-encodeable/src/parsers/createFormatterFromFieldTypeAndFormat.ts
  packages/superset-ui-encodeable/src/parsers/createGetterFromChannelDef.ts
  packages/superset-ui-encodeable/src/parsers/fallbackFormatter.ts
  packages/superset-ui-encodeable/src/types/ChannelDef.ts
  packages/superset-ui-encodeable/test/parsers/createFormatterFromChannelDef.test.ts
  packages/superset-ui-encodeable/test/parsers/createFormatterFromFieldTypeAndFormat.test.ts
  packages/superset-ui-encodeable/test/parsers/createGetterFromChannelDef.test.ts
  packages/superset-ui-encodeable/test/parsers/fallbackFormatter.test.ts
Labels: reviewable, size/L

#214 refactor: rename encodeable to encodable
  CHANGELOG.md
  packages/superset-ui-encodable/README.md
  packages/superset-ui-encodable/package.json
  packages/superset-ui-encodable/src/index.ts
  packages/superset-ui-encodable/src/parsers/createGetterFromChannelDef.ts
  packages/superset-ui-encodable/src/parsers/format/createFormatterFromChannelDef.ts
  packages/superset-ui-encodable/src/parsers/format/createFormatterFromFieldTypeAndFormat.ts
  packages/superset-ui-encodable/src/parsers/format/fallbackFormatter.ts
  packages/superset-ui-encodable/src/parsers/parseDateTime.ts
  packages/superset-ui-encodable/src/parsers/scale/applyAlign.ts
  packages/superset-ui-encodable/src/parsers/scale/applyClamp.ts
  packages/superset-ui-encodable/src/parsers/scale/applyDomain.ts
  packages/superset-ui-encodable/src/parsers/scale/applyInterpolate.ts
  packages/superset-ui-encodable/src/parsers/scale/applyNice.ts
  packages/superset-ui-encodable/src/parsers/scale/applyPadding.ts
  packages/superset-ui-encodable/src/parsers/scale/applyRange.ts
  packages/superset-ui-encodable/src/parsers/scale/applyRound.ts
  packages/superset-ui-encodable/src/parsers/scale/applyZero.ts
  packages/superset-ui-encodable/src/parsers/scale/createScaleFromScaleConfig.ts
  packages/superset-ui-encodable/src/parsers/scale/createScaleFromScaleType.ts
  packages/superset-ui-encodable/src/parsers/scale/getScaleCategoryFromScaleType.ts
  packages/superset-ui-encodable/src/parsers/scale/inferScaleType.ts
  packages/superset-ui-encodable/src/parsers/scale/isPropertySupportedByScaleType.ts
  packages/superset-ui-encodable/src/parsers/scale/scaleCategories.ts
  packages/superset-ui-encodable/src/typeGuards/Base.ts
  packages/superset-ui-encodable/src/typeGuards/ChannelDef.ts
  packages/superset-ui-encodable/src/typeGuards/Scale.ts
  packages/superset-ui-encodable/src/types/Axis.ts
  packages/superset-ui-encodable/src/types/Base.ts
  packages/superset-ui-encodable/src/types/Channel.ts
  packages/superset-ui-encodable/src/types/ChannelDef.ts
  packages/superset-ui-encodable/src/types/Data.ts
  packages/superset-ui-encodable/src/types/Legend.ts
  packages/superset-ui-encodable/src/types/Scale.ts
  packages/superset-ui-encodable/src/types/VegaLite.ts
  packages/superset-ui-encodable/src/utils/identity.ts
  packages/superset-ui-encodable/src/utils/inferElementTypeFromUnionOfArrayTypes.ts
  packages/superset-ui-encodable/src/utils/isDisabled.ts
  packages/superset-ui-encodable/src/utils/isEnabled.ts
  packages/superset-ui-encodable/test/parsers/createGetterFromChannelDef.test.ts
  packages/superset-ui-encodable/test/parsers/format/createFormatterFromChannelDef.test.ts
  packages/superset-ui-encodable/test/parsers/format/createFormatterFromFieldTypeAndFormat.test.ts
  packages/superset-ui-encodable/test/parsers/format/fallbackFormatter.test.ts
  packages/superset-ui-encodable/test/parsers/parseDateTime.test.ts
  packages/superset-ui-encodable/test/parsers/scale/createScaleFromScaleConfig.test.ts
  packages/superset-ui-encodable/test/parsers/scale/getScaleCategoryFromScaleType.test.ts
  packages/superset-ui-encodable/test/parsers/scale/inferScaleType.test.ts
  packages/superset-ui-encodable/test/parsers/scale/isPropertySupportedByScaleType.test.ts
  packages/superset-ui-encodable/test/typeGuards/Base.test.ts
  packages/superset-ui-encodable/test/typeGuards/ChannelDef.test.ts
  packages/superset-ui-encodable/test/typeGuards/Scale.test.ts
  packages/superset-ui-encodable/test/utils/identity.test.ts
  packages/superset-ui-encodable/test/utils/isDisabled.test.ts
  packages/superset-ui-encodable/test/utils/isEnabled.test.ts
  packages/superset-ui-encodeable/README.md
Labels: #code-quality, reviewable
