Repository apache-superset/superset-ui, pull requests merged in 2019-03, with the labels that each got.

#120 feat(chart): Add `<ChartDataProvider />`
  package.json
  packages/superset-ui-chart/README.md
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-chart/src/components/ChartDataProvider.tsx
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/models/ChartProps.ts
  packages/superset-ui-chart/src/types/ChartFormData.ts
  packages/superset-ui-chart/src/types/Datasource.ts
  packages/superset-ui-chart/test/clients/ChartClient.test.ts
  packages/superset-ui-chart/test/components/ChartDataProvider.test.tsx
  packages/superset-ui-chart/test/components/SuperChart.test.jsx
  packages/superset-ui-chart/test/components/SuperChart.test.tsx
  packages/superset-ui-chart/test/fixtures/formData.ts
  packages/superset-ui-chart/test/models/ChartPlugin.test.ts
  packages/superset-ui-connection/src/SupersetClient.ts
  packages/superset-ui-connection/test/SupersetClient.test.ts
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/stories/index.js
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/ChartDataProviderStories.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/index.ts
  packages/superset-ui-demo/storybook/stories/superset-ui-connection/ConnectionStories.jsx
  types/external.d.ts
Labels: #feature, reviewable

#121 chore(chart): remove faux @superset-ui/core TS declaration
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-chart/src/components/SuperChart.tsx
  packages/superset-ui-chart/src/models/ChartMetadata.ts
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/src/registries/ChartBuildQueryRegistrySingleton.ts
  packages/superset-ui-chart/src/registries/ChartComponentRegistrySingleton.ts
  packages/superset-ui-chart/src/registries/ChartMetadataRegistrySingleton.ts
  packages/superset-ui-chart/src/registries/ChartTransformPropsRegistrySingleton.ts
  packages/superset-ui-chart/src/types/Query.ts
  packages/superset-ui-chart/test/clients/ChartClient.test.ts
  packages/superset-ui-chart/test/components/SuperChart.test.tsx
  packages/superset-ui-chart/test/models/ChartPlugin.test.tsx
  packages/superset-ui-chart/types/external.d.ts
  packages/superset-ui-core/src/models/Registry.ts
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/ChartDataProviderStories.tsx
Labels: #code-quality, reviewable

#122 fix(chart): import types from package, not monorepo
  package.json
  packages/superset-ui-chart/src/components/ChartDataProvider.tsx
Labels: #bug, #build

#123 fix: 🐛 Fixed type definition for chart plugin
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/src/types/Query.ts
  packages/superset-ui-chart/test/components/SuperChart.test.tsx
Labels: #bug, reviewable

#113 chore: enforce check on PR title to be conventional commit
  .github/semantic.yml
Labels: #build, #code-quality, reviewable
