Repository apache-superset/superset-ui, pull requests merged in 2019-04, with the labels that each got.

#119 feat: add support for conditional requests
  package.json
  packages/superset-ui-connection/README.md
  packages/superset-ui-connection/src/callApi/callApi.ts
  packages/superset-ui-connection/src/constants.ts
  packages/superset-ui-connection/test/callApi/callApi.test.ts
  test/setupTests.ts
Labels: #enhancement, reviewable

#126 Revert "Handle BigNumber conversions in JSON properly (without loss of precision) (#71)"
  package.json
  packages/superset-ui-chart/test/components/ChartDataProvider.test.tsx
  packages/superset-ui-connection/package.json
  packages/superset-ui-connection/src/callApi/parseResponse.ts
  packages/superset-ui-connection/test/SupersetClientClass.test.ts
  packages/superset-ui-connection/test/callApi/parseResponse.test.ts
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/shared/components/VerifyCORS.tsx
  packages/superset-ui-demo/types/external.d.ts
  types/external.d.ts
Labels: #bug, reviewable

#131 feat: callback hooks for Reactified components
  packages/superset-ui-chart/src/components/reactify.tsx
  packages/superset-ui-chart/test/components/reactify.test.tsx
Labels: #enhancement, reviewable, size/S

#132 fix: smartDateVerbose at seconds
  packages/superset-ui-time-format/src/formatters/smartDateVerbose.ts
Labels: size/XS

#130 chore: add config for request-info bot
  .github/config.yml
Labels: size/S

#134 docs: update readme
  README.md
Labels: size/S

#135 chore: create issue_label_bot.yaml
  .github/issue_label_bot.yaml
Labels: size/XS

#136 fix: bump peer dependencies
  packages/superset-ui-chart/package.json
  packages/superset-ui-color/package.json
  packages/superset-ui-number-format/package.json
  packages/superset-ui-time-format/package.json
Labels: size/S

#140 fix: make translation module type check correctly
  packages/superset-ui-translation/src/TranslatorSingleton.ts
Labels: size/S

#141 fix: broken build due to failing unit tests
  packages/superset-ui-connection/test/callApi/callApi.test.ts
Labels: size/M

#139 feat: add chart companion components
  packages/superset-ui-chart-composition/README.md
  packages/superset-ui-chart-composition/__mocks__/resize-observer-polyfill.js
  packages/superset-ui-chart-composition/package.json
  packages/superset-ui-chart-composition/src/ChartFrame.tsx
  packages/superset-ui-chart-composition/src/index.ts
  packages/superset-ui-chart-composition/src/legend/WithLegend.tsx
  packages/superset-ui-chart-composition/src/tooltip/TooltipFrame.tsx
  packages/superset-ui-chart-composition/src/tooltip/TooltipTable.tsx
  packages/superset-ui-chart-composition/test/ChartFrame.test.tsx
  packages/superset-ui-chart-composition/test/legend/WithLegend.test.tsx
  packages/superset-ui-chart-composition/test/tooltip/TooltipFrame.test.tsx
  packages/superset-ui-chart-composition/test/tooltip/TooltipTable.test.tsx
  packages/superset-ui-chart-composition/types/@vx/responsive/index.d.ts
Labels: size/XL
