Repository apache-superset/superset-ui, pull requests merged in 2019-06, with the labels that each got.

#167 build: bump build-config
  package.json
  packages/superset-ui-connection/test/SupersetClientClass.test.ts
Labels: size/XS

#168 feat: allow chart plugin to be unregistered
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/test/models/ChartPlugin.test.tsx
  packages/superset-ui-core/src/models/Plugin.ts
  packages/superset-ui-core/test/models/Plugin.test.ts
Labels: #enhancement, reviewable, size/M

#169 refactor: separate transform function types into a new file
  packages/superset-ui-chart/src/components/SuperChart.tsx
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/src/models/ChartProps.ts
  packages/superset-ui-chart/src/registries/ChartTransformPropsRegistrySingleton.ts
  packages/superset-ui-chart/src/types/Base.ts
  packages/superset-ui-chart/src/types/Query.ts
  packages/superset-ui-chart/src/types/TransformFunction.ts
Labels: #code-quality, reviewable, size/M

#172 test: extract mock plugins into separate file
  packages/superset-ui-chart/test/components/MockChartPlugins.tsx
  packages/superset-ui-chart/test/components/SuperChart.test.tsx
Labels: size/L

#171 feat: add parseLength function to @superset-ui/dimension
  packages/superset-ui-dimension/src/index.ts
  packages/superset-ui-dimension/src/parseLength.ts
  packages/superset-ui-dimension/test/parseLength.test.ts
Labels: reviewable, size/M

#175 feat: add error boundary and responsiveness to SuperChart
  package.json
  packages/superset-ui-chart/__mocks__/resize-observer-polyfill.js
  packages/superset-ui-chart/package.json
  packages/superset-ui-chart/src/components/FallbackComponent.tsx
  packages/superset-ui-chart/src/components/SuperChart.tsx
  packages/superset-ui-chart/src/components/SuperChartCore.tsx
  packages/superset-ui-chart/src/components/SuperChartShell.tsx
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/models/ChartProps.ts
  packages/superset-ui-chart/test/components/FallbackComponent.test.tsx
  packages/superset-ui-chart/test/components/MockChartPlugins.tsx
  packages/superset-ui-chart/test/components/SuperChart.test.tsx
  packages/superset-ui-chart/test/components/SuperChartCore.test.tsx
  packages/superset-ui-chart/test/components/SuperChartShell.test.tsx
  packages/superset-ui-chart/test/components/promiseTimeout.tsx
  packages/superset-ui-chart/types/@vx/responsive/index.d.ts
  packages/superset-ui-demo/.storybook/config.js
  packages/superset-ui-demo/.storybook/webpack.config.js
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/index.ts
Labels: #enhancement, reviewable, size/XXL

#180 feat: store reference to container and update bindings
  packages/superset-ui-chart/src/components/SuperChart.tsx
  packages/superset-ui-chart/src/components/SuperChartCore.tsx
  packages/superset-ui-chart/src/components/SuperChartShell.tsx
Labels: #code-quality, #enhancement, reviewable, size/L

#183 fix: wrong type for filters field
  packages/superset-ui-chart/src/models/ChartProps.ts
Labels: size/XS

#182 feat: support locale in number and time format
  packages/superset-ui-number-format/src/factories/createD3NumberFormatter.ts
  packages/superset-ui-number-format/test/factories/createD3NumberFormatter.test.ts
  packages/superset-ui-time-format/src/factories/createD3TimeFormatter.ts
  packages/superset-ui-time-format/test/factories/createD3TimeFormatter.test.js
  packages/superset-ui-time-format/test/factories/createD3TimeFormatter.test.ts
Labels: #enhancement, reviewable, size/L

#184 fix: move eslint disable comment in reactify test
  packages/superset-ui-chart/test/components/reactify.test.tsx
Labels: size/XS

#185 fix: clean up unneeded Promise.resolves()
  packages/superset-ui-connection/src/SupersetClientClass.ts
  packages/superset-ui-connection/test/SupersetClientClass.test.ts
  packages/superset-ui-connection/test/callApi/callApi.test.ts
  packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
  packages/superset-ui-connection/test/callApi/parseResponse.test.ts
Labels: size/M
