Repository apache-superset/superset-ui, pull requests merged in 2019-11, with the labels that each got.

#236 feat: add function for getting legend information
  packages/superset-ui-encodable/src/encoders/ChannelEncoder.ts
  packages/superset-ui-encodable/src/encoders/Encoder.ts
  packages/superset-ui-encodable/src/types/Encoding.ts
  packages/superset-ui-encodable/test/encoders/Encoder.test.ts
Labels: size/L

#245 build: fix lint
  packages/superset-ui-chart/src/components/SuperChart.tsx
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-core/test/models/Registry.test.ts
  packages/superset-ui-encodable/src/encoders/createEncoderFactory.ts
  packages/superset-ui-encodable/src/fillers/completeAxisConfig.ts
  packages/superset-ui-number-format/src/index.ts
  packages/superset-ui-query/src/types/Query.ts
Labels: size/M

#244 feat(time-format): bump d3-time-format
  packages/superset-ui-time-format/package.json
Labels: size/XS

#246 fix: d3-scale typings
  packages/superset-ui-encodable/package.json
  packages/superset-ui-encodable/src/index.ts
  packages/superset-ui-encodable/src/types/Scale.ts
  packages/superset-ui-encodable/types/d3-scale/index.d.ts
Labels: size/XXL

#248 refactor: rename .getDomain() to .getDomainFromDataset()
  packages/superset-ui-encodable/src/encoders/ChannelEncoder.ts
  packages/superset-ui-encodable/src/encoders/Encoder.ts
  packages/superset-ui-encodable/test/encoders/ChannelEncoder.test.ts
Labels: size/S

#251 build: fix lodash type dependencies
  packages/superset-ui-core/package.json
Labels: size/XS

#250 feat(encodable): only set scale domain if both bounds are defined
  packages/superset-ui-encodable/src/parsers/scale/applyDomain.ts
  packages/superset-ui-encodable/src/typeGuards/Base.ts
  packages/superset-ui-encodable/src/typeGuards/Scale.ts
  packages/superset-ui-encodable/src/types/Scale.ts
  packages/superset-ui-encodable/test/parsers/scale/createScaleFromScaleConfig.test.ts
  packages/superset-ui-encodable/test/typeGuards/Base.test.ts
  packages/superset-ui-encodable/test/typeGuards/Scale.test.ts
Labels: size/L

#254 feat(encodable): make applyDomain() able to handle domain from dataset
  packages/superset-ui-encodable/src/parsers/domain/parseContinuousDomain.ts
  packages/superset-ui-encodable/src/parsers/domain/parseDiscreteDomain.ts
  packages/superset-ui-encodable/src/parsers/parseDateTimeIfPossible.ts
  packages/superset-ui-encodable/src/parsers/scale/applyDomain.ts
  packages/superset-ui-encodable/src/typeGuards/Base.ts
  packages/superset-ui-encodable/src/types/Scale.ts
  packages/superset-ui-encodable/src/utils/combineCategories.ts
  packages/superset-ui-encodable/src/utils/combineContinuousDomains.ts
  packages/superset-ui-encodable/test/parsers/domain/parseContinuousDomain.test.ts
  packages/superset-ui-encodable/test/parsers/domain/parseDiscreteDomain.test.ts
  packages/superset-ui-encodable/test/parsers/scale/applyDomain.test.ts
  packages/superset-ui-encodable/test/utils/combineCategories.test.ts
  packages/superset-ui-encodable/test/utils/combineContinuousDomains.test.ts
Labels: size/L

#247 feat(encodable): implement axis functions for ChannelEncoder
  packages/superset-ui-encodable/src/encoders/ChannelEncoder.ts
  packages/superset-ui-encodable/src/encoders/ChannelEncoderAxis.ts
  packages/superset-ui-encodable/src/parsers/parseDateTimeIfPossible.ts
  packages/superset-ui-encodable/src/types/VegaLite.ts
  packages/superset-ui-encodable/test/encoders/ChannelEncoderAxis.test.ts
Labels: size/L

#257 feat(encodable): handle edge cases when making domain includes zero
  packages/superset-ui-encodable/src/parsers/scale/applyZero.ts
  packages/superset-ui-encodable/test/parsers/scale/applyZero.test.ts
  packages/superset-ui-encodable/test/parsers/scale/createScaleFromScaleConfig.test.ts
Labels: size/M

#256 feat(encodable): add function for setting domain
  packages/superset-ui-encodable/src/encoders/ChannelEncoder.ts
  packages/superset-ui-encodable/src/parsers/scale/applyDomain.ts
  packages/superset-ui-encodable/src/types/Scale.ts
  packages/superset-ui-encodable/src/utils/removeUndefinedAndNull.ts
  packages/superset-ui-encodable/test/encoders/ChannelEncoder.test.ts
  packages/superset-ui-encodable/test/parsers/scale/applyDomain.test.ts
Labels: size/L

#255 feat: add @superset-ui/superset-ui package as one-stop install
  packages/superset-ui-superset-ui/README.md
  packages/superset-ui-superset-ui/package.json
  packages/superset-ui-superset-ui/src/index.ts
  packages/superset-ui-superset-ui/test/index.test.ts
Labels: size/L

#260 fix: typing issues surfaced by typescript 3.7
  package.json
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-chart/src/components/ChartDataProvider.tsx
Labels: size/M

#261 fix(dimension): set width=0, height=0 in `createHiddenSvgNode`
  packages/superset-ui-dimension/src/svg/createHiddenSvgNode.ts
Labels: size/XS

#262 feat(number-format): bump pretty-ms to 5.1.0
  packages/superset-ui-number-format/package.json
Labels: size/XS
