Repository apache-superset/superset-ui, pull requests merged in 2019-05, with the labels that each got.

#144 fix: lint
  packages/superset-ui-chart/src/components/SuperChart.tsx
Labels: size/S

#156 Updated Readme with missing yarn build command.
  README.md
Labels: size/XS

#158 feat: add hooks field to ChartProps
  packages/superset-ui-chart/src/models/ChartProps.ts
Labels: size/XS

#159 feat: improve margin merging with NaN and null
  packages/superset-ui-dimension/src/mergeMargin.ts
  packages/superset-ui-dimension/test/mergeMargin.test.ts
Labels: size/M

#164 feat: update ChartFormData and QueryObject to support filters.
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/query/Metrics.ts
  packages/superset-ui-chart/src/query/buildQueryObject.ts
  packages/superset-ui-chart/src/query/convertFilter.ts
  packages/superset-ui-chart/src/query/convertMetric.ts
  packages/superset-ui-chart/src/query/processExtras.ts
  packages/superset-ui-chart/src/query/processFilters.ts
  packages/superset-ui-chart/src/query/processMetrics.ts
  packages/superset-ui-chart/src/types/ChartFormData.ts
  packages/superset-ui-chart/src/types/Datasource.ts
  packages/superset-ui-chart/src/types/Filter.ts
  packages/superset-ui-chart/src/types/Metric.ts
  packages/superset-ui-chart/src/types/Operator.ts
  packages/superset-ui-chart/src/types/Query.ts
  packages/superset-ui-chart/src/types/Time.ts
  packages/superset-ui-chart/test/query/Metrics.test.ts
  packages/superset-ui-chart/test/query/convertFilter.test.ts
  packages/superset-ui-chart/test/query/convertMetric.test.ts
  packages/superset-ui-chart/test/query/processFilters.test.ts
  packages/superset-ui-chart/test/query/processMetrics.test.ts
  packages/superset-ui-chart/test/types/Filter.test.ts
  packages/superset-ui-demo/.storybook/webpack.config.js
Labels: size/XXL
