Repository apache-superset/superset-ui, pull requests merged in 2020-10, with the labels that each got.

#803 fix(generator-superset): add fixes to viz plugin generator
  packages/generator-superset/generators/plugin-chart/index.js
  packages/generator-superset/generators/plugin-chart/templates/README.erb
  packages/generator-superset/generators/plugin-chart/templates/src/MyChart.erb
  packages/generator-superset/generators/plugin-chart/templates/src/plugin/controlPanel.erb
  packages/generator-superset/generators/plugin-chart/templates/src/plugin/index.erb
  packages/generator-superset/generators/plugin-chart/templates/src/plugin/transformProps.erb
  packages/generator-superset/generators/plugin-chart/templates/src/types.erb
  packages/generator-superset/generators/plugin-chart/templates/tsconfig.json
Labels: size/L

#804 chore(plugin-chart-echarts): rename boxplot type to whisker_type
  plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
  plugins/plugin-chart-echarts/src/BoxPlot/types.ts
Labels: size/S

#808 fix(legacy-preset-chart-nvd3): custom yAxisFormat for contribution
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
Labels: size/S

#809 feat(core): add applied_time_extras to QueryObject
  packages/superset-ui-core/src/query/extractExtras.ts
  packages/superset-ui-core/src/query/types/Query.ts
  packages/superset-ui-core/src/query/types/Time.ts
  packages/superset-ui-core/test/query/extractExtras.test.ts
Labels: size/M

#810 fix(plugin-chart-echarts): fix default y axis bounds
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
Labels: size/XS

#812 feat(core): add support for annotations and url params
  packages/superset-ui-core/src/query/buildQueryObject.ts
  packages/superset-ui-core/src/query/index.ts
  packages/superset-ui-core/src/query/types/AnnotationLayer.ts
  packages/superset-ui-core/src/query/types/Query.ts
  packages/superset-ui-core/src/query/types/QueryFormData.ts
  packages/superset-ui-core/test/query/buildQueryObject.test.ts
  packages/superset-ui-core/test/query/types/AnnotationFilter.test.ts
Labels: size/L

#816 fix(plugin-chart-echarts): disable pie chart animation
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
Labels: size/XS

#815 fix(plugin-chart-echarts): improve yAxisBounds parsing
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/utils/controls.ts
  plugins/plugin-chart-echarts/test/utils/controls.test.ts
Labels: size/M

#818 feat: update time_compare description and choices
  plugins/legacy-plugin-chart-partition/src/controlPanel.jsx
  plugins/legacy-plugin-chart-rose/src/controlPanel.jsx
  plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
Labels: size/S

#817 feat(plugin-chart-echarts): add support for formula annotations
  packages/superset-ui-core/src/query/types/AnnotationLayer.ts
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/utils/annotation.ts
  plugins/plugin-chart-echarts/test/Timeseries/transformProps.test.ts
  plugins/plugin-chart-echarts/test/utils/annotation.test.ts
  yarn.lock
Labels: size/L

#820 feat(plugin-chart-echarts): make boxplot groupby optional
  plugins/plugin-chart-echarts/src/BoxPlot/controlPanel.ts
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
  plugins/plugin-chart-echarts/test/BoxPlot/transformProps.test.ts
  plugins/plugin-chart-echarts/test/utils/series.test.ts
Labels: size/M
