Repository apache-superset/superset-ui, pull requests merged in 2020-04, with the labels that each got.

#322 feat: add validator package
  packages/superset-ui-validator/README.md
  packages/superset-ui-validator/package.json
  packages/superset-ui-validator/src/index.ts
  packages/superset-ui-validator/src/legacyValidateInteger.ts
  packages/superset-ui-validator/src/legacyValidateNumber.ts
  packages/superset-ui-validator/src/validateInteger.ts
  packages/superset-ui-validator/src/validateNonEmpty.ts
  packages/superset-ui-validator/src/validateNumber.ts
  packages/superset-ui-validator/test/legacyValidateInteger.test.ts
  packages/superset-ui-validator/test/legacyValidateNumber.test.ts
  packages/superset-ui-validator/test/validateInteger.test.ts
  packages/superset-ui-validator/test/validateNonEmpty.test.ts
  packages/superset-ui-validator/test/validateNumber.test.ts
  test/setup.ts
Labels: size/L

#327 feat: add validator to umbrella package
  packages/superset-ui-superset-ui/package.json
  packages/superset-ui-superset-ui/src/index.ts
  packages/superset-ui-superset-ui/test/index.test.ts
Labels: size/XS

#340 fix(legacy-plugin-chart-table): time column formatting
  codecov.yml
  plugins/table/src/ReactDataTable.tsx
  plugins/table/src/transformProps.ts
  plugins/table/test/ReactDataTable.test.tsx
  plugins/table/test/testData.ts
Labels: size/M

#352 feat: allow toggling of table viz's bar chart backgrounds
  package.json
  packages/superset-ui-demo/storybook/stories/plugins/table/TableStories.tsx
  packages/superset-ui-demo/tsconfig.json
  plugins/table/src/ReactDataTable.tsx
  plugins/table/src/transformProps.ts
  plugins/table/test/testData.ts
Labels: size/S

#357 feat: make CategoricalScale compatible with D3's ScaleOrdinal
  packages/superset-ui-color/src/CategoricalColorScale.ts
  packages/superset-ui-color/test/CategoricalColorScale.test.ts
Labels: size/L

#358 feat: make time formatter handle number and fix formatters type warnings
  packages/superset-ui-core/test/models/ExtensibleFunction.test.ts
  packages/superset-ui-number-format/src/NumberFormatter.ts
  packages/superset-ui-time-format/src/TimeFormatter.ts
  packages/superset-ui-time-format/test/TimeFormatter.test.ts
Labels: size/M

#363 build: disable commit lint
  package.json
  yarn.lock
Labels: size/XL

#362 feat: style package for theming and styled components
  packages/superset-ui-style/README.md
  packages/superset-ui-style/package.json
  packages/superset-ui-style/src/index.ts
  packages/superset-ui-style/test/index.test.ts
Labels: size/L

#369 build: add github workflow for build and test
  .github/workflows/ci.yml
Labels: reviewable, size/M

#373 build: disable travis
  .travis.yml
Labels: reviewable, size/S

#366 feat: add style to umbrella package
  packages/superset-ui-superset-ui/package.json
  packages/superset-ui-superset-ui/src/index.ts
  packages/superset-ui-superset-ui/test/index.test.ts
Labels: reviewable, size/XS

#368 feat: migrate 4 chart plugins
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-paired-t-test/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-paired-t-test/data.ts
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-parallel-coordinates/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-parallel-coordinates/data.ts
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-partition/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-partition/data.ts
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-pivot-table/Stories.tsx
  plugins/legacy-plugin-chart-paired-t-test/README.md
  plugins/legacy-plugin-chart-paired-t-test/package.json
  plugins/legacy-plugin-chart-paired-t-test/src/PairedTTest.css
  plugins/legacy-plugin-chart-paired-t-test/src/PairedTTest.jsx
  plugins/legacy-plugin-chart-paired-t-test/src/TTestTable.jsx
  plugins/legacy-plugin-chart-paired-t-test/src/images/thumbnail.png
  plugins/legacy-plugin-chart-paired-t-test/src/images/thumbnailLarge.png
  plugins/legacy-plugin-chart-paired-t-test/src/index.js
  plugins/legacy-plugin-chart-paired-t-test/src/transformProps.js
  plugins/legacy-plugin-chart-parallel-coordinates/README.md
  plugins/legacy-plugin-chart-parallel-coordinates/package.json
  plugins/legacy-plugin-chart-parallel-coordinates/src/ParallelCoordinates.css
  plugins/legacy-plugin-chart-parallel-coordinates/src/ParallelCoordinates.js
  plugins/legacy-plugin-chart-parallel-coordinates/src/ReactParallelCoordinates.js
  plugins/legacy-plugin-chart-parallel-coordinates/src/images/thumbnail.png
  plugins/legacy-plugin-chart-parallel-coordinates/src/images/thumbnailLarge.png
  plugins/legacy-plugin-chart-parallel-coordinates/src/index.js
  plugins/legacy-plugin-chart-parallel-coordinates/src/transformProps.js
  plugins/legacy-plugin-chart-parallel-coordinates/src/vendor/parcoords/d3.parcoords.css
  plugins/legacy-plugin-chart-parallel-coordinates/src/vendor/parcoords/d3.parcoords.js
  plugins/legacy-plugin-chart-parallel-coordinates/src/vendor/parcoords/divgrid.js
  plugins/legacy-plugin-chart-partition/README.md
  plugins/legacy-plugin-chart-partition/package.json
  plugins/legacy-plugin-chart-partition/src/Partition.css
  plugins/legacy-plugin-chart-partition/src/Partition.js
  plugins/legacy-plugin-chart-partition/src/ReactPartition.js
  plugins/legacy-plugin-chart-partition/src/images/thumbnail.png
  plugins/legacy-plugin-chart-partition/src/images/thumbnailLarge.png
  plugins/legacy-plugin-chart-partition/src/index.js
  plugins/legacy-plugin-chart-partition/src/transformProps.js
  plugins/legacy-plugin-chart-pivot-table/README.md
  plugins/legacy-plugin-chart-pivot-table/package.json
  plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
  plugins/legacy-plugin-chart-pivot-table/src/ReactPivotTable.js
  plugins/legacy-plugin-chart-pivot-table/src/images/thumbnail.png
  plugins/legacy-plugin-chart-pivot-table/src/images/thumbnailLarge.png
  plugins/legacy-plugin-chart-pivot-table/src/index.js
  plugins/legacy-plugin-chart-pivot-table/src/transformProps.js
  plugins/legacy-plugin-chart-pivot-table/src/utils/fixTableHeight.js
  yarn.lock
Labels: reviewable

#344 feat(table): enable table filter and better typing
  package.json
  packages/superset-ui-chart-composition/package.json
  packages/superset-ui-chart/package.json
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-chart/src/components/ChartDataProvider.tsx
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/src/models/ChartProps.ts
  packages/superset-ui-chart/src/types/QueryResponse.ts
  packages/superset-ui-chart/test/models/ChartProps.test.ts
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/stories/plugins/table/birthNames.json
  packages/superset-ui-query/src/types/Datasource.ts
  packages/superset-ui-query/src/types/Query.ts
  plugins/big-number/src/BigNumber/transformProps.ts
  plugins/big-number/src/utils/getTimeFormatterForGranularity.ts
  plugins/big-number/test/transformProps.test.ts
  plugins/table/package.json
  plugins/table/src/ReactDataTable.tsx
  plugins/table/src/Table.css
  plugins/table/src/transformProps.ts
  plugins/table/test/testData.ts
  scripts/build.js
  yarn.lock
Labels: size/L

#384 feat: add retry to callApi
  packages/superset-ui-connection/package.json
  packages/superset-ui-connection/src/SupersetClientClass.ts
  packages/superset-ui-connection/src/callApi/callApi.ts
  packages/superset-ui-connection/src/constants.ts
  packages/superset-ui-connection/src/types.ts
  packages/superset-ui-connection/test/callApi/callApi.test.ts
  yarn.lock
Labels: size/M

#387 fix: unset row_limit when it's not a number
  packages/superset-ui-query/src/buildQueryObject.ts
Labels: size/XS

#378 fix: make all filter operators uppercase
  packages/superset-ui-query/src/types/Operator.ts
  packages/superset-ui-query/test/convertFilter.test.ts
  packages/superset-ui-query/test/types/Filter.test.ts
Labels: size/S

#390 fix(superset-ui-query): add unit tests for #387
  packages/superset-ui-query/src/buildQueryObject.ts
  packages/superset-ui-query/src/types/QueryFormData.ts
  packages/superset-ui-query/test/buildQueryContext.test.ts
  packages/superset-ui-query/test/buildQueryObject.test.ts
Labels: size/M

#389 chore: add shared plugin controls utilities
  package.json
  packages/superset-ui-chart/README.md
  packages/superset-ui-chart/package.json
  packages/superset-ui-chart/src/controls/D3Formatting.ts
  packages/superset-ui-chart/src/controls/index.ts
  packages/superset-ui-chart/src/controls/sections.tsx
  packages/superset-ui-chart/src/controls/selectOptions.ts
  packages/superset-ui-chart/src/index.ts
  packages/superset-ui-chart/test/controls/selectOptions.test.ts
  temporary-plugins/superset-ui-legacy-preset-chart-nvd3/src/NVD3Controls.tsx
Labels: size/XL

#398 chore: bump pretty-ms
  packages/superset-ui-number-format/package.json
  packages/superset-ui-number-format/test/factories/createDurationFormatter.test.ts
Labels: size/XS

#391 fix: export superset theme props
  packages/superset-ui-style/src/index.ts
  packages/superset-ui-style/test/index.test.ts
Labels: size/S

#422 chore(legacy-plugin-chart-table): rename directories
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-table/TableStories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-table/birthNames.json
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-table/data.js
  plugins/legacy-plugin-chart-table/README.md
  plugins/legacy-plugin-chart-table/package.json
  plugins/legacy-plugin-chart-table/src/ReactDataTable.tsx
  plugins/legacy-plugin-chart-table/src/Table.css
  plugins/legacy-plugin-chart-table/src/images/thumbnail.png
  plugins/legacy-plugin-chart-table/src/images/thumbnailLarge.png
  plugins/legacy-plugin-chart-table/src/index.ts
  plugins/legacy-plugin-chart-table/src/transformProps.ts
  plugins/legacy-plugin-chart-table/test/ReactDataTable.test.tsx
  plugins/legacy-plugin-chart-table/test/testData.ts
  plugins/legacy-plugin-chart-table/types/external.d.ts
Labels: reviewable

#421 feat(superset-ui): include control utils in the umbrella package
  packages/superset-ui-superset-ui/package.json
  packages/superset-ui-superset-ui/src/index.ts
  packages/superset-ui-superset-ui/test/index.test.ts
Labels: reviewable, size/XS

#428 fix(plugin-chart-word-cloud): make wordcloud take current formdata
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-word-cloud/Stories.tsx
  plugins/plugin-chart-word-cloud/src/chart/WordCloud.tsx
  plugins/plugin-chart-word-cloud/src/plugin/index.ts
Labels: size/S

#420 fix: lint errors
  packages/superset-ui-chart-composition/src/ChartFrame.tsx
  packages/superset-ui-chart-composition/test/legend/WithLegend.test.tsx
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-chart/src/components/ChartDataProvider.tsx
  packages/superset-ui-chart/src/components/SuperChart.tsx
  packages/superset-ui-chart/src/components/SuperChartCore.tsx
  packages/superset-ui-chart/src/components/createLoadableRenderer.ts
  packages/superset-ui-chart/src/models/ChartControlPanel.ts
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/src/models/ChartProps.ts
  packages/superset-ui-chart/src/types/Base.ts
  packages/superset-ui-chart/src/types/TransformFunction.ts
  packages/superset-ui-chart/test/components/SuperChart.test.tsx
  packages/superset-ui-chart/test/components/reactify.test.tsx
  packages/superset-ui-chart/test/models/ChartProps.test.ts
  packages/superset-ui-connection/test/callApi/rejectAfterTimeout.test.ts
  packages/superset-ui-connection/test/utils/throwIfCalled.ts
  packages/superset-ui-core/src/models/Plugin.ts
  packages/superset-ui-core/src/utils/convertKeysToCamelCase.ts
  packages/superset-ui-core/src/utils/isDefined.ts
  packages/superset-ui-core/src/utils/makeSingleton.ts
  packages/superset-ui-core/src/utils/promiseTimeout.ts
  packages/superset-ui-core/test/models/Preset.test.ts
  packages/superset-ui-core/test/models/Registry.test.ts
  packages/superset-ui-core/test/utils/makeSingleton.test.ts
  plugins/legacy-plugin-chart-heatmap/src/Heatmap.js
  plugins/legacy-plugin-chart-horizon/src/HorizonRow.jsx
  plugins/legacy-plugin-chart-map-box/src/ScatterPlotGlowOverlay.jsx
  plugins/legacy-plugin-chart-map-box/src/utils/geo.js
  plugins/legacy-plugin-chart-paired-t-test/src/TTestTable.jsx
  plugins/legacy-plugin-chart-partition/src/Partition.js
  plugins/legacy-plugin-chart-rose/src/Rose.js
  plugins/legacy-plugin-chart-sunburst/src/Sunburst.js
  plugins/legacy-plugin-chart-sunburst/src/utils/wrapSvgText.js
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/preset-chart-xy/src/components/Line/Line.tsx
Labels: reviewable, size/L
