Repository apache-superset/superset-ui, pull requests merged in 2020-11, with the labels that each got.

#823 fix(plugin-chart-echarts): fix broken boxplot storybook example
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/BoxPlot/data.ts
Labels: size/M

#826 chore: bump yarn.lock
  yarn.lock
Labels: size/XL

#821 fix: point version badge to npm page
  README.md
  packages/generator-superset/README.md
  packages/generator-superset/generators/plugin-chart/templates/README.erb
  packages/superset-ui-chart-controls/README.md
  packages/superset-ui-core/README.md
  packages/superset-ui-demo/README.md
  plugins/legacy-plugin-chart-calendar/README.md
  plugins/legacy-plugin-chart-chord/README.md
  plugins/legacy-plugin-chart-country-map/README.md
  plugins/legacy-plugin-chart-event-flow/README.md
  plugins/legacy-plugin-chart-force-directed/README.md
  plugins/legacy-plugin-chart-heatmap/README.md
  plugins/legacy-plugin-chart-histogram/README.md
  plugins/legacy-plugin-chart-horizon/README.md
  plugins/legacy-plugin-chart-map-box/README.md
  plugins/legacy-plugin-chart-paired-t-test/README.md
  plugins/legacy-plugin-chart-parallel-coordinates/README.md
  plugins/legacy-plugin-chart-partition/README.md
  plugins/legacy-plugin-chart-pivot-table/README.md
  plugins/legacy-plugin-chart-rose/README.md
  plugins/legacy-plugin-chart-sankey-loop/README.md
  plugins/legacy-plugin-chart-sankey/README.md
  plugins/legacy-plugin-chart-sunburst/README.md
  plugins/legacy-plugin-chart-time-table/README.md
  plugins/legacy-plugin-chart-treemap/README.md
  plugins/legacy-plugin-chart-world-map/README.md
  plugins/legacy-preset-chart-big-number/README.md
  plugins/legacy-preset-chart-nvd3/README.md
  plugins/plugin-chart-choropleth-map/README.md
  plugins/plugin-chart-echarts/README.md
  plugins/plugin-chart-table/README.md
  plugins/plugin-chart-word-cloud/README.md
  plugins/preset-chart-xy/README.md
Labels: size/L

#825 chore(chart-controls): clean up typing
  packages/superset-ui-chart-controls/src/components/InfoTooltipWithTrigger.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-chart-controls/src/types.ts
  yarn.lock
Labels: size/XL

#831 feat(legacy-plugin-chart-sankey): allow sort by metric
  plugins/legacy-plugin-chart-sankey/src/controlPanel.ts
Labels: size/M

#828 feat(plugin-chart-echarts): implement event interval and timeseries annotations
  packages/superset-ui-core/src/query/types/AnnotationLayer.ts
  packages/superset-ui-core/test/query/types/AnnotationFilter.test.ts
  packages/superset-ui-core/test/query/types/AnnotationLayer.test.ts
  plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
  plugins/plugin-chart-echarts/src/utils/annotation.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
  plugins/plugin-chart-echarts/test/Timeseries/transformProps.test.ts
  plugins/plugin-chart-echarts/test/tsconfig.json
  plugins/plugin-chart-echarts/test/utils/annotation.test.ts
  plugins/plugin-chart-echarts/test/utils/series.test.ts
Labels: size/XXL

#832 chore: bump mathjs to latest version on all plugins
  plugins/legacy-preset-chart-nvd3/package.json
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/plugin-chart-echarts/package.json
  yarn.lock
Labels: size/XXL

#839 fix(legacy-plugin-chart-pivot-table): remove nulls from table
  plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
Labels: size/XS

#843 feat: add rison request type to makeApi
  packages/superset-ui-core/package.json
  packages/superset-ui-core/src/query/api/v1/makeApi.ts
  packages/superset-ui-core/test/query/api/v1/makeApi.test.ts
Labels: size/S
