Repository apache-superset/superset-ui, pull requests merged in 2020-08, with the labels that each got.

#723 build: upgrade codecov-action and disable failing_ci_if_error
  .github/workflows/ci.yml
Labels: size/S

#721 feat: align metrics title to the right
  plugins/plugin-chart-table/src/DataTable/DataTable.tsx
  plugins/plugin-chart-table/src/DataTable/hooks/useColumnCellProps.ts
  plugins/plugin-chart-table/src/DataTable/index.tsx
  plugins/plugin-chart-table/src/DataTable/types/react-table.d.ts
  plugins/plugin-chart-table/src/TableChart.tsx
Labels: size/L

#711 feat: improve world map colors
  plugins/legacy-plugin-chart-world-map/package.json
  plugins/legacy-plugin-chart-world-map/src/WorldMap.js
  plugins/legacy-plugin-chart-world-map/src/controlPanel.js
  plugins/legacy-plugin-chart-world-map/src/transformProps.js
Labels: size/M

#724 feat: properly translate the table chart
  package.json
  packages/superset-ui-core/src/index.ts
  packages/superset-ui-core/src/utils/logging.ts
  packages/superset-ui-core/test/utils/logging.test.ts
  packages/superset-ui-translation/package.json
  packages/superset-ui-translation/src/Translator.ts
  packages/superset-ui-translation/src/TranslatorSingleton.ts
  packages/superset-ui-translation/src/index.ts
  packages/superset-ui-translation/src/types.ts
  packages/superset-ui-translation/src/types/index.ts
  packages/superset-ui-translation/src/types/jed.ts
  packages/superset-ui-translation/test/Translator.test.ts
  packages/superset-ui-translation/test/languagePacks/en.ts
  packages/superset-ui-translation/test/languagePacks/zh.ts
  plugins/plugin-chart-table/src/DataTable/DataTable.tsx
  plugins/plugin-chart-table/src/DataTable/components/SelectPageSize.tsx
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/controlPanel.tsx
  plugins/plugin-chart-table/src/i18n.ts
Labels: size/XL

#713 fix: dist bar will render value multi times
  plugins/legacy-preset-chart-nvd3/src/utils.js
  yarn.lock
Labels: size/XS

#738 feat: logger supports console.table, with console.log fallback
  packages/superset-ui-core/src/utils/logging.ts
  packages/superset-ui-core/test/utils/logging.test.ts
Labels: size/S

#734 feat(legacy-plugin-chart-pivot-table): add support for timestamp format
  plugins/legacy-plugin-chart-pivot-table/package.json
  plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
  plugins/legacy-plugin-chart-pivot-table/src/controlPanel.js
  plugins/legacy-plugin-chart-pivot-table/src/transformProps.js
Labels: size/L

#744 build: update encodable dependency
  package.json
  packages/superset-ui-demo/.storybook/preview.js
  packages/superset-ui-demo/package.json
  plugins/plugin-chart-choropleth-map/package.json
  plugins/plugin-chart-choropleth-map/src/configureEncodable.ts
  plugins/plugin-chart-choropleth-map/src/index.ts
  plugins/plugin-chart-word-cloud/package.json
  plugins/plugin-chart-word-cloud/src/configureEncodable.ts
  plugins/plugin-chart-word-cloud/src/index.ts
  plugins/preset-chart-xy/package.json
  plugins/preset-chart-xy/src/configureEncodable.ts
  plugins/preset-chart-xy/src/index.ts
  yarn.lock
Labels: size/XL

#748 feat: add certification icon to metrics
  packages/superset-ui-chart-controls/src/components/CertifiedIconWithTooltip.tsx
  packages/superset-ui-chart-controls/src/components/MetricOption.tsx
Labels: size/M

#692 chore(legacy-chart-nvd3): convert nvd3 to emotion style
  plugins/legacy-preset-chart-nvd3/package.json
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.css
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/legacy-preset-chart-nvd3/src/ReactNVD3.js
  plugins/legacy-preset-chart-nvd3/src/ReactNVD3.jsx
Labels: size/L

#752 chore: silencing console errors by making MetricOption props optional
  packages/superset-ui-chart-controls/src/components/MetricOption.tsx
Labels: size/S

#754 chore: clean up a couple of TypeScript warnings
  packages/superset-ui-chart-controls/src/components/MetricOption.tsx
  packages/superset-ui-chart-controls/src/index.ts
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-chart-controls/src/types.ts
  packages/superset-ui-chart-controls/src/utils/mainMetric.ts
  packages/superset-ui-translation/src/Translator.ts
  plugins/legacy-plugin-chart-time-table/src/TimeTable.tsx
  plugins/legacy-plugin-chart-time-table/src/transformProps.ts
  yarn.lock
Labels: size/M

#751 feat(color): add official ECharts color schemes
  packages/superset-ui-color/src/colorSchemes/categorical/echarts.ts
  packages/superset-ui-color/src/colorSchemes/sequential/common.ts
  packages/superset-ui-color/test/colorSchemes.test.ts
  packages/superset-ui-demo/storybook/stories/superset-ui-color/ColorPallettesStories.jsx
Labels: size/M
