Repository apache-superset/superset-ui, pull requests merged in 2020-07, with the labels that each got.

#653 build: bump nvd3-fork with tooltip fix
  plugins/legacy-preset-chart-nvd3/package.json
  yarn.lock
Labels: size/S

#659 fix(plugin-chart-table): change default queryMode to null
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/XS

#661 fix(plugin-chart-table): anchor should keep href
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/birthNames.json
  plugins/plugin-chart-table/src/utils/formatValue.ts
Labels: size/S

#663 fix(plugin-chart-table): formatting non-numeric metrics
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/TableStories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/testData.ts
  plugins/plugin-chart-table/src/transformProps.ts
  plugins/plugin-chart-table/src/types.ts
  yarn.lock
Labels: size/XL

#634 feat(connection): easier API for json payload
  package.json
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-connection/src/SupersetClientClass.ts
  packages/superset-ui-connection/src/callApi/callApi.ts
  packages/superset-ui-connection/src/types.ts
  packages/superset-ui-connection/test/callApi/callApi.test.ts
  packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
  packages/superset-ui-demo/storybook/shared/components/VerifyCORS.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-connection/ConnectionStories.tsx
  packages/superset-ui-query/src/api/types.ts
  packages/superset-ui-query/src/api/v1/postChartData.ts
Labels: size/L

#635 feat(connection): optimize typing and API for SupersetClient
  packages/superset-ui-chart/test/components/MockChartPlugins.tsx
  packages/superset-ui-connection/src/SupersetClient.ts
  packages/superset-ui-connection/src/SupersetClientClass.ts
  packages/superset-ui-connection/src/callApi/callApi.ts
  packages/superset-ui-connection/src/callApi/callApiAndParseWithTimeout.ts
  packages/superset-ui-connection/src/callApi/parseResponse.ts
  packages/superset-ui-connection/src/callApi/rejectAfterTimeout.ts
  packages/superset-ui-connection/src/types.ts
  packages/superset-ui-connection/test/SupersetClient.test.ts
  packages/superset-ui-connection/test/SupersetClientClass.test.ts
  packages/superset-ui-connection/test/callApi/callApi.test.ts
  packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
  packages/superset-ui-connection/test/callApi/parseResponse.test.ts
  packages/superset-ui-connection/test/callApi/rejectAfterTimeout.test.ts
  packages/superset-ui-connection/test/fixtures/constants.ts
  packages/superset-ui-connection/test/utils/throwIfCalled.ts
  packages/superset-ui-demo/storybook/shared/components/ErrorMessage.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/ChartDataProviderStories.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-connection/ConnectionStories.tsx
Labels: size/XXL

#669 fix(plugin-chart-table): sort and search time column
  plugins/plugin-chart-table/src/Styles.tsx
  plugins/plugin-chart-table/src/transformProps.ts
  plugins/plugin-chart-table/src/utils/DateWithFormatter.ts
  plugins/plugin-chart-table/test/TableChart.test.tsx
  yarn.lock
Labels: size/L

#676 chore: requiresTime not required
  plugins/legacy-plugin-chart-calendar/src/controlPanel.js
  plugins/legacy-plugin-chart-event-flow/src/controlPanel.jsx
  plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts
  plugins/legacy-plugin-chart-rose/src/controlPanel.jsx
  plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bullet/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Compare/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Line/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/TimePivot/controlPanel.ts
Labels: size/S

#675 chore: Cleaning up control overrides
  plugins/legacy-plugin-chart-heatmap/src/controlPanel.js
  plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
Labels: size/S

#643 chore(chart-forced-directed): use emotion style
  plugins/legacy-plugin-chart-force-directed/package.json
  plugins/legacy-plugin-chart-force-directed/src/ForceDirected.css
  plugins/legacy-plugin-chart-force-directed/src/ForceDirected.js
  plugins/legacy-plugin-chart-force-directed/src/ReactForceDirected.jsx
  plugins/legacy-plugin-chart-force-directed/src/index.js
  plugins/legacy-plugin-chart-pivot-table/package.json
Labels: size/M

#652 chore(chart-worldmap): use emotion style
  plugins/legacy-plugin-chart-world-map/package.json
  plugins/legacy-plugin-chart-world-map/src/ReactWorldMap.js
  plugins/legacy-plugin-chart-world-map/src/ReactWorldMap.jsx
  plugins/legacy-plugin-chart-world-map/src/WorldMap.js
  plugins/legacy-plugin-chart-world-map/src/index.js
Labels: size/M

#651 chore(chart-sankey): use emotion styling typography
  plugins/legacy-plugin-chart-sankey/package.json
  plugins/legacy-plugin-chart-sankey/src/ReactSankey.js
  plugins/legacy-plugin-chart-sankey/src/ReactSankey.jsx
  plugins/legacy-plugin-chart-sankey/src/Sankey.css
  plugins/legacy-plugin-chart-sankey/src/Sankey.js
  plugins/legacy-plugin-chart-sankey/src/index.js
Labels: size/L

#680 feat(legacy-time-table): add time table to storybook
  packages/superset-ui-demo/.storybook/main.js
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-time-table/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-time-table/data.ts
Labels: size/L

#686 fix(plugin-chart-table): value undefined when table name has dot
  packages/superset-ui-chart-composition/package.json
  packages/superset-ui-chart/package.json
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/testData.ts
  plugins/legacy-plugin-chart-time-table/package.json
  plugins/plugin-chart-choropleth-map/package.json
  plugins/plugin-chart-table/package.json
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/test/TableChart.test.tsx
  plugins/plugin-chart-table/test/testData.ts
  plugins/plugin-chart-word-cloud/package.json
  scripts/build.js
  temporary-plugins/package.json
  temporary-plugins/superset-ui-plugins-demo/package.json
  yarn.lock
Labels: size/M

#688 fix: implement extra filter logic
  packages/superset-ui-query/src/buildQueryObject.ts
  packages/superset-ui-query/src/extractExtras.ts
  packages/superset-ui-query/src/processExtras.ts
  packages/superset-ui-query/src/processFilters.ts
  packages/superset-ui-query/src/types/Query.ts
  packages/superset-ui-query/src/types/QueryFormData.ts
  packages/superset-ui-query/test/extractExtras.test.ts
  packages/superset-ui-query/test/processFilters.test.ts
  plugins/plugin-chart-word-cloud/src/plugin/buildQuery.ts
Labels: size/L

#693 fix(legacy-plugin-chart-treemap): incorrect template literal
  plugins/legacy-plugin-chart-treemap/src/Treemap.js
Labels: size/XS

#696 feat(legacy-plugin-chart-rose): add time grain
  plugins/legacy-plugin-chart-rose/src/controlPanel.jsx
Labels: size/XS

#695 fix(legacy-plugin-chart-pivot-table): formatting non-numeric values
  plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
Labels: size/XS

#700 fix(query): equals operator, duplicate filters and time range endpoints
  packages/superset-ui-query/src/buildQueryObject.ts
  packages/superset-ui-query/src/extractExtras.ts
  packages/superset-ui-query/src/processFilters.ts
  packages/superset-ui-query/src/types/Operator.ts
  packages/superset-ui-query/src/types/QueryFormData.ts
  packages/superset-ui-query/test/convertFilter.test.ts
  packages/superset-ui-query/test/extractExtras.test.ts
  packages/superset-ui-query/test/processFilters.test.ts
  packages/superset-ui-query/test/types/Filter.test.ts
Labels: size/M

#641 chore(plugin-chart-parallel-coordinates): convert para coords chart to emotion styling
  plugins/legacy-plugin-chart-parallel-coordinates/package.json
  plugins/legacy-plugin-chart-parallel-coordinates/src/ParallelCoordinates.css
  plugins/legacy-plugin-chart-parallel-coordinates/src/ParallelCoordinates.js
  plugins/legacy-plugin-chart-parallel-coordinates/src/ReactParallelCoordinates.jsx
  plugins/legacy-plugin-chart-parallel-coordinates/src/index.js
Labels: size/M

#703 fix: charts rerender with zero-height during tab switch
  plugins/legacy-plugin-chart-world-map/src/WorldMap.js
  plugins/legacy-plugin-chart-world-map/src/transformProps.js
  plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx
Labels: size/S

#699 feat(legacy-preset-chart-nvd3): add a new label type to pie chart
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/legacy-preset-chart-nvd3/src/Pie/controlPanel.ts
Labels: size/S

#714 feat(legacy-plugin-chart-sunburst): add linear color scheme
  plugins/legacy-plugin-chart-sunburst/src/Sunburst.js
  plugins/legacy-plugin-chart-sunburst/src/controlPanel.ts
  plugins/legacy-plugin-chart-sunburst/src/transformProps.js
Labels: size/M

#715 fix: add timeout value to error details in rejectAfterTimeout
  packages/superset-ui-connection/src/callApi/rejectAfterTimeout.ts
  packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
Labels: size/XS

#718 feat: style pkg exports emotion's css module
  packages/superset-ui-style/src/index.ts
Labels: size/XS
