Repository apache-superset/superset-ui, pull requests merged in 2020-05, with the labels that each got.

#432 feat(calendar): add calendar control panel
  plugins/legacy-plugin-chart-calendar/package.json
  plugins/legacy-plugin-chart-calendar/src/controlPanel.js
  plugins/legacy-plugin-chart-calendar/src/index.js
Labels: size/L

#444 fix(legacy-plugin-world-map): set useLegacyApi to true by default
  plugins/legacy-plugin-chart-world-map/src/index.js
Labels: size/XS

#445 fix: Add force to QueryContext
  packages/superset-ui-chart/test/models/ChartPlugin.test.tsx
  packages/superset-ui-query/src/buildQueryContext.ts
  packages/superset-ui-query/src/types/Query.ts
  packages/superset-ui-query/src/types/QueryFormData.ts
  packages/superset-ui-query/test/buildQueryContext.test.ts
Labels: size/S

#443 chore: pulling in Sunburst controls from incubator-superset
  plugins/legacy-plugin-chart-sunburst/package.json
  plugins/legacy-plugin-chart-sunburst/src/controlPanel.ts
  plugins/legacy-plugin-chart-sunburst/src/index.js
Labels: size/M

#453 fix: Remove .ts suffix from NVD3 imports
  plugins/legacy-preset-chart-nvd3/src/transformProps.js
  plugins/legacy-preset-chart-nvd3/test/utils/tokenize.test.js
Labels: size/XS

#447 fix: lint again
  packages/superset-ui-chart/src/models/ChartPlugin.ts
  packages/superset-ui-chart/test/components/ChartDataProvider.test.tsx
  packages/superset-ui-chart/test/components/MockChartPlugins.tsx
  packages/superset-ui-chart/test/components/createLoadableRenderer.test.tsx
  packages/superset-ui-connection/src/callApi/callApi.ts
  packages/superset-ui-connection/src/types.ts
  packages/superset-ui-connection/test/SupersetClient.test.ts
  packages/superset-ui-connection/test/SupersetClientClass.test.ts
  packages/superset-ui-connection/test/callApi/callApi.test.ts
  packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
  packages/superset-ui-connection/test/callApi/parseResponse.test.ts
  packages/superset-ui-translation/src/Translator.ts
  packages/superset-ui-translation/src/TranslatorSingleton.ts
  plugins/legacy-plugin-chart-table/src/ReactDataTable.tsx
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/preset-chart-xy/src/BoxPlot/legacy/transformProps.ts
  plugins/preset-chart-xy/src/BoxPlot/transformProps.ts
  plugins/preset-chart-xy/src/ScatterPlot/legacy/transformProps.ts
  plugins/preset-chart-xy/src/components/BoxPlot/BoxPlot.tsx
  plugins/preset-chart-xy/src/components/Line/Line.tsx
  plugins/preset-chart-xy/src/components/ScatterPlot/ScatterPlot.tsx
Labels: size/L

#442 feat(control-utils): add infotooltipwithtrigger
  packages/superset-ui-control-utils/package.json
  packages/superset-ui-control-utils/src/InfoTooltipWithTrigger.tsx
  packages/superset-ui-control-utils/src/index.ts
  packages/superset-ui-control-utils/test/InfoTooltipWithTrigger.test.tsx
Labels: size/L

#454 feat(plugin-chart-word-cloud): add control panel
  plugins/plugin-chart-word-cloud/package.json
  plugins/plugin-chart-word-cloud/src/plugin/controlPanel.ts
  plugins/plugin-chart-word-cloud/src/plugin/index.ts
  yarn.lock
Labels: size/L

#462 feat(plugin-chart-world-map): add control panel
  plugins/legacy-plugin-chart-world-map/package.json
  plugins/legacy-plugin-chart-world-map/src/controlPanel.js
  plugins/legacy-plugin-chart-world-map/src/index.js
Labels: size/L

#461 feat(plugin-chart-treemap): add control panel
  plugins/legacy-plugin-chart-treemap/package.json
  plugins/legacy-plugin-chart-treemap/src/controlPanel.js
  plugins/legacy-plugin-chart-treemap/src/index.js
Labels: size/M

#457 feat(plugin-chart-pivot-table): add control panel
  plugins/legacy-plugin-chart-pivot-table/package.json
  plugins/legacy-plugin-chart-pivot-table/src/controlPanel.js
  plugins/legacy-plugin-chart-pivot-table/src/index.js
Labels: size/L

#458 feat(plugin-chart-rose): add rose chart controls
  plugins/legacy-plugin-chart-rose/package.json
  plugins/legacy-plugin-chart-rose/src/controlPanel.jsx
  plugins/legacy-plugin-chart-rose/src/index.js
Labels: size/L

#464 feat(plugin-chart-boxplot): add control panel
  plugins/preset-chart-xy/package.json
  plugins/preset-chart-xy/src/BoxPlot/controlPanel.ts
  plugins/preset-chart-xy/src/BoxPlot/index.ts
  plugins/preset-chart-xy/src/BoxPlot/legacy/index.ts
Labels: size/M

#471 chore: enforce commit-lint on first commit in branch
  package.json
  packages/superset-ui-chart/README.md
  scripts/commitlint.js
Labels: size/S

#463 feat(style): adding typographic variables to theme
  packages/superset-ui-style/src/index.ts
Labels: size/S

#469 feat(legacy-plugin-chart-nvd3): add control panels
  plugins/legacy-preset-chart-nvd3/package.json
  plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Area/index.js
  plugins/legacy-preset-chart-nvd3/src/Bar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bar/index.js
  plugins/legacy-preset-chart-nvd3/src/Bubble/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bubble/index.js
  plugins/legacy-preset-chart-nvd3/src/Bullet/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bullet/index.js
  plugins/legacy-preset-chart-nvd3/src/Compare/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Compare/index.js
  plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/DistBar/index.js
  plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/DualLine/index.js
  plugins/legacy-preset-chart-nvd3/src/Line/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Line/index.js
  plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/LineMulti/index.js
  plugins/legacy-preset-chart-nvd3/src/Pie/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Pie/index.js
  plugins/legacy-preset-chart-nvd3/src/TimePivot/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/TimePivot/index.js
Labels: size/XXL

#468 test: be more lenient on jsx/tsx test coverage
  codecov.yml
Labels: size/S

#480 build: resolving lerna commitlint/scoping issue
  lerna.json
Labels: size/XS

#479 feat(legacy-plugin-chart-markup): add controls to markup chart
  plugins/legacy-plugin-chart-markup/package.json
  plugins/legacy-plugin-chart-markup/src/controlPanel.js
  plugins/legacy-plugin-chart-markup/src/index.js
Labels: size/M

#459 feat(control-utils): add shared controls + dependencies, convert to typescript
  packages/superset-ui-control-utils/package.json
  packages/superset-ui-control-utils/src/ColumnOption.tsx
  packages/superset-ui-control-utils/src/ColumnTypeLabel.tsx
  packages/superset-ui-control-utils/src/constants.ts
  packages/superset-ui-control-utils/src/index.ts
  packages/superset-ui-control-utils/src/mainMetric.ts
  packages/superset-ui-control-utils/src/shared-controls.tsx
  packages/superset-ui-control-utils/test/ColumnOption.test.tsx
  packages/superset-ui-control-utils/test/ColumnTypeLabel.test.tsx
  packages/superset-ui-control-utils/test/mainMetric.test.ts
Labels: size/XL

#482 test: codecov ignore tsx/jsx
  codecov.yml
Labels: size/XS

#481 feat(legacy-plugin-chart-chord): control panel
  plugins/legacy-plugin-chart-chord/package.json
  plugins/legacy-plugin-chart-chord/src/controlPanel.js
  plugins/legacy-plugin-chart-chord/src/index.js
Labels: size/M

#488 fix(legacy-plugin-chart-nvd3): disable bad linting rule
  package.json
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-calendar/Stories.tsx
  plugins/legacy-plugin-chart-sunburst/src/index.js
  plugins/legacy-preset-chart-nvd3/src/Area/index.js
  plugins/legacy-preset-chart-nvd3/src/Bar/index.js
  plugins/legacy-preset-chart-nvd3/src/Bubble/index.js
  plugins/legacy-preset-chart-nvd3/src/Bullet/index.js
  plugins/legacy-preset-chart-nvd3/src/Compare/index.js
  plugins/legacy-preset-chart-nvd3/src/DistBar/index.js
  plugins/legacy-preset-chart-nvd3/src/DualLine/index.js
  plugins/legacy-preset-chart-nvd3/src/Line/index.js
  plugins/legacy-preset-chart-nvd3/src/LineMulti/index.js
  plugins/legacy-preset-chart-nvd3/src/Pie/index.js
  plugins/legacy-preset-chart-nvd3/src/TimePivot/index.js
  plugins/legacy-preset-chart-nvd3/src/transformProps.js
  plugins/legacy-preset-chart-nvd3/test/utils/tokenize.test.js
Labels: size/S

#487 feat(plugin-chart-word-cloud): allow minimum size
  plugins/plugin-chart-word-cloud/src/legacyPlugin/transformProps.ts
  plugins/plugin-chart-word-cloud/src/legacyPlugin/types.ts
  plugins/plugin-chart-word-cloud/test/legacyPlugin/transformProps.test.ts
Labels: size/S

#456 feat(generator-superset): add scaffolder for chart plugin
  packages/generator-superset/generators/app/index.js
  packages/generator-superset/generators/plugin-chart/index.js
  packages/generator-superset/generators/plugin-chart/templates/README.erb
  packages/generator-superset/generators/plugin-chart/templates/package.erb
  packages/generator-superset/generators/plugin-chart/templates/src/MyChart.erb
  packages/generator-superset/generators/plugin-chart/templates/src/images/thumbnail.png
  packages/generator-superset/generators/plugin-chart/templates/src/index.erb
  packages/generator-superset/generators/plugin-chart/templates/src/plugin/index.erb
  packages/generator-superset/generators/plugin-chart/templates/src/plugin/transformProps.txt
  packages/generator-superset/generators/plugin-chart/templates/test/index.erb
  packages/generator-superset/generators/plugin-chart/templates/types/external.d.ts
  packages/generator-superset/test/plugin-chart.test.js
  yarn.lock
Labels: reviewable

#486 feat(time-format): add full-date to weekly time formatter
  packages/superset-ui-demo/storybook/stories/plugins/legacy-preset-chart-big-number/BigNumber/BigNumberStories.tsx
  packages/superset-ui-time-format/src/factories/getTimeFormatterForGranularity.ts
  packages/superset-ui-time-format/src/index.ts
  packages/superset-ui-time-format/src/types.ts
  packages/superset-ui-time-format/test/factories/getTimeFormatterForGranularity.test.ts
  plugins/legacy-preset-chart-big-number/src/BigNumber/transformProps.ts
  plugins/legacy-preset-chart-big-number/test/transformProps.test.ts
Labels: size/M

#492 feat(query): remove redundant metric label truncation
  packages/superset-ui-query/src/convertMetric.ts
  packages/superset-ui-query/test/convertMetric.test.ts
Labels: size/S

#493 fix(time-format): remove week number
  packages/superset-ui-time-format/src/factories/getTimeFormatterForGranularity.ts
  packages/superset-ui-time-format/test/factories/getTimeFormatterForGranularity.test.ts
Labels: size/S

#507 feat(legacy-plugin-chart-map-box): control panel
  plugins/legacy-plugin-chart-map-box/package.json
  plugins/legacy-plugin-chart-map-box/src/controlPanel.js
  plugins/legacy-plugin-chart-map-box/src/index.js
Labels: size/L

#505 feat(legacy-plugin-chart-horizon): control panel
  plugins/legacy-plugin-chart-horizon/package.json
  plugins/legacy-plugin-chart-horizon/src/controlPanel.js
  plugins/legacy-plugin-chart-horizon/src/index.js
Labels: size/M

#504 feat(legacy-plugin-chart-histogram): control panel
  plugins/legacy-plugin-chart-histogram/package.json
  plugins/legacy-plugin-chart-histogram/src/controlPanel.js
  plugins/legacy-plugin-chart-histogram/src/index.js
Labels: size/L

#502 feat(legacy-plugin-chart-force-directed): control panel
  plugins/legacy-plugin-chart-force-directed/package.json
  plugins/legacy-plugin-chart-force-directed/src/controlPanel.js
  plugins/legacy-plugin-chart-force-directed/src/index.js
Labels: size/M

#503 feat(legacy-plugin-chart-heatmap): control panel
  plugins/legacy-plugin-chart-heatmap/package.json
  plugins/legacy-plugin-chart-heatmap/src/controlPanel.js
  plugins/legacy-plugin-chart-heatmap/src/index.js
Labels: size/L

#501 feat(legacy-plugin-chart-event-flow): control panel
  temporary-plugins/hold-potentially-deprecate/superset-ui-legacy-plugin-chart-event-flow/package.json
  temporary-plugins/hold-potentially-deprecate/superset-ui-legacy-plugin-chart-event-flow/src/controlPanel.jsx
  temporary-plugins/hold-potentially-deprecate/superset-ui-legacy-plugin-chart-event-flow/src/index.js
Labels: size/L

#508 chore: so 514 tablechart plugin controls migration
  plugins/legacy-plugin-chart-table/package.json
  plugins/legacy-plugin-chart-table/src/controlPanel.tsx
  plugins/legacy-plugin-chart-table/src/index.ts
Labels: size/L

#485 feat: add control grouping functionality
  packages/superset-ui-control-utils/src/shared-controls.tsx
  packages/superset-ui-query/src/buildQueryObject.ts
  packages/superset-ui-query/src/convertMetric.ts
  packages/superset-ui-query/src/extractQueryFields.ts
  packages/superset-ui-query/src/processGroupby.ts
  packages/superset-ui-query/src/processMetrics.ts
  packages/superset-ui-query/src/types/Metric.ts
  packages/superset-ui-query/src/types/Query.ts
  packages/superset-ui-query/src/types/QueryFormData.ts
  packages/superset-ui-query/test/buildQueryObject.test.ts
  packages/superset-ui-query/test/extractQueryFields.test.ts
  packages/superset-ui-query/test/processGroupby.test.ts
  packages/superset-ui-query/test/processMetrics.test.ts
  plugins/plugin-chart-word-cloud/src/plugin/buildQuery.ts
  plugins/plugin-chart-word-cloud/test/plugin/buildQuery.test.ts
Labels: size/L

#455 feat(legacy-preset-big-number): use emotion styling
  packages/superset-ui-demo/.storybook/preview.js
  packages/superset-ui-demo/.storybook/themeDecorator.js
  packages/superset-ui-style/README.md
  plugins/big-number/yarn.lock
  plugins/legacy-preset-chart-big-number/package.json
  plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.css
  plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.tsx
Labels: size/XXL

#510 feat(legacy-plugin-chart-parallel-coordinates): add control panels
  plugins/legacy-plugin-chart-parallel-coordinates/package.json
  plugins/legacy-plugin-chart-parallel-coordinates/src/controlPanel.ts
  plugins/legacy-plugin-chart-parallel-coordinates/src/index.js
Labels: size/M

#517 fix: missing bracket, little linty things
  plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.tsx
Labels: size/S

#515 chore: paired t test chart plugin control migration
  plugins/legacy-plugin-chart-paired-t-test/package.json
  plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts
  plugins/legacy-plugin-chart-paired-t-test/src/index.js
Labels: size/M

#519 fix(legacy-plugin-chart-parallel-coordinates): remove .ts ext from import in para
  plugins/legacy-plugin-chart-parallel-coordinates/src/index.js
Labels: size/XS

#521 chore(legacy-plugin-chart-table): cleanup fromFormData
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-table/birthNames.json
Labels: size/S

#520 fix(legacy-plugin-chart-paired-t-test): remove ts from import
  plugins/legacy-plugin-chart-paired-t-test/src/index.js
Labels: size/XS

#522 fix(legacy-plugin-chart-table): parse numeric pageLength
  plugins/legacy-plugin-chart-table/src/transformProps.ts
  plugins/legacy-plugin-chart-table/test/ReactDataTable.test.tsx
  plugins/legacy-plugin-chart-table/test/testData.ts
Labels: size/S

#516 chore(legacy-plugin-chart-country-map): add controls to chart
  plugins/legacy-plugin-chart-country-map/package.json
  plugins/legacy-plugin-chart-country-map/src/controlPanel.ts
  plugins/legacy-plugin-chart-country-map/src/index.js
Labels: size/L

#528 feat(plugin-chart-choropleth-map): add zooming
  plugins/plugin-chart-choropleth-map/package.json
  plugins/plugin-chart-choropleth-map/src/chart/ChoroplethMap.tsx
  plugins/plugin-chart-choropleth-map/src/chart/components.ts
  yarn.lock
Labels: size/L

#540 fix: nvd3 annotation tooltip
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.css
Labels: size/XS

#518 feat: Word cloud typography update
  plugins/plugin-chart-word-cloud/package.json
  plugins/plugin-chart-word-cloud/src/chart/Encoder.ts
  plugins/plugin-chart-word-cloud/src/chart/WordCloud.tsx
  plugins/plugin-chart-word-cloud/src/legacyPlugin/index.ts
  plugins/plugin-chart-word-cloud/src/legacyPlugin/transformProps.ts
  plugins/plugin-chart-word-cloud/src/plugin/index.ts
  yarn.lock
Labels: size/M

#546 docs: simplified npm link for dev debugging
  docs/debugging.md
  docs/storybook.md
Labels: size/M

#541 feat(plugin-chart-choropleth-map): add encoding
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-choropleth-map/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-choropleth-map/generateFakeMapData.ts
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-choropleth-map/useFakeMapData.ts
  plugins/plugin-chart-choropleth-map/src/chart/ChoroplethMap.tsx
  plugins/plugin-chart-choropleth-map/src/chart/Encoder.ts
  plugins/plugin-chart-choropleth-map/src/plugin/transformProps.ts
Labels: size/L

#547 feat(color): support better color interpolation for sequential schemes
  packages/superset-ui-color/package.json
  packages/superset-ui-color/src/SequentialScheme.ts
  packages/superset-ui-color/test/SequentialScheme.test.ts
Labels: size/L

#551 feat(chart): adjust chartclient to point to new endpoints
  packages/superset-ui-chart/src/clients/ChartClient.ts
  packages/superset-ui-chart/test/clients/ChartClient.test.ts
Labels: size/M

#552 feat: allow developer to get supersetclient instance
  packages/superset-ui-connection/src/SupersetClient.ts
Labels: size/S
