Repository apache-superset/superset-ui, pull requests merged in 2020-06, with the labels that each got.

#553 feat(superset-ui-style): export ThemeProvider and useTheme
  packages/superset-ui-demo/.storybook/themeDecorator.js
  packages/superset-ui-style/README.md
  packages/superset-ui-style/package.json
  packages/superset-ui-style/src/index.ts
  plugins/plugin-chart-word-cloud/package.json
  plugins/plugin-chart-word-cloud/src/chart/WordCloud.tsx
Labels: size/S

#557 feat(demo): add helpers for resizable chart demo
  packages/superset-ui-demo/.storybook/storybook.css
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/shared/components/ResizableChartDemo.tsx
  packages/superset-ui-demo/storybook/shared/components/ResizablePanel.tsx
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-table/TableStories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-word-cloud/Stories.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx
  yarn.lock
Labels: size/L

#555 feat(query): add functions to wrap api calls with typings
  packages/superset-ui-query/package.json
  packages/superset-ui-query/src/api/legacy/fetchExploreJson.ts
  packages/superset-ui-query/src/api/legacy/types.ts
  packages/superset-ui-query/src/api/v1/postChartData.ts
  packages/superset-ui-query/src/api/v1/types.ts
  packages/superset-ui-query/src/index.ts
  packages/superset-ui-query/test/api/fixtures/constants.ts
  packages/superset-ui-query/test/api/legacy/fetchExploreJson.test.ts
  packages/superset-ui-query/test/api/v1/postChartData.test.ts
Labels: size/L

#571 build: allow building only one (or more) package
  CONTRIBUTING.md
  README.md
  package.json
  scripts/build.js
  scripts/copyAssets.js
Labels: size/M

#570 feat(query): add more query wrappers
  packages/superset-ui-query/src/api/legacy/fetchExploreJson.ts
  packages/superset-ui-query/src/api/legacy/getDatasourceMetadata.ts
  packages/superset-ui-query/src/api/legacy/getFormData.ts
  packages/superset-ui-query/src/api/legacy/index.ts
  packages/superset-ui-query/src/api/types.ts
  packages/superset-ui-query/src/api/v1/index.ts
  packages/superset-ui-query/src/api/v1/postChartData.ts
  packages/superset-ui-query/src/index.ts
  packages/superset-ui-query/test/api/fixtures/constants.ts
  packages/superset-ui-query/test/api/legacy/fetchExploreJson.test.ts
  packages/superset-ui-query/test/api/legacy/getDatasourceMetadata.test.ts
  packages/superset-ui-query/test/api/legacy/getFormData.test.ts
  packages/superset-ui-query/test/api/setupClientForTest.ts
  packages/superset-ui-query/test/api/v1/postChartData.test.ts
Labels: size/L

#583 feat(query): add new fields to QueryContext and QueryObject
  packages/superset-ui-chart/test/models/ChartPlugin.test.tsx
  packages/superset-ui-query/src/buildQueryContext.ts
  packages/superset-ui-query/src/buildQueryObject.ts
  packages/superset-ui-query/src/types/Query.ts
  packages/superset-ui-query/src/types/QueryFormData.ts
  packages/superset-ui-query/test/buildQueryContext.test.ts
  packages/superset-ui-query/test/buildQueryObject.test.ts
  packages/superset-ui-query/test/processGroupby.test.ts
Labels: size/M

#567 chore(Markup chart): add emotion styling to Markup chart
  plugins/legacy-plugin-chart-markup/package.json
  plugins/legacy-plugin-chart-markup/src/Markup.css
  plugins/legacy-plugin-chart-markup/src/Markup.jsx
Labels: size/M

#586 style(control-utils): fix type reexport warning in babel
  packages/superset-ui-control-utils/src/ColumnOption.tsx
  packages/superset-ui-control-utils/src/ColumnTypeLabel.tsx
  packages/superset-ui-control-utils/src/InfoTooltipWithTrigger.tsx
  packages/superset-ui-control-utils/src/index.ts
  packages/superset-ui-control-utils/src/shared-controls.tsx
  packages/superset-ui-control-utils/test/ColumnOption.test.tsx
  packages/superset-ui-control-utils/test/ColumnTypeLabel.test.tsx
Labels: size/M

#594 fix: annotation PropType for formula annotations
  plugins/legacy-preset-chart-nvd3/src/PropTypes.js
Labels: size/XS

#593 chore(superset-ui-control-uitils): add MetricOption and dependencies to control utils
  packages/superset-ui-control-utils/package.json
  packages/superset-ui-control-utils/src/MetricOption.tsx
  packages/superset-ui-control-utils/src/index.ts
  packages/superset-ui-control-utils/test/components/ColumnOption.test.tsx
  packages/superset-ui-control-utils/test/components/ColumnTypeLabel.test.tsx
  packages/superset-ui-control-utils/test/components/InfoTooltipWithTrigger.test.tsx
  packages/superset-ui-control-utils/test/components/MetricOption.test.tsx
Labels: size/L

#561 chore: calender chart typography
  plugins/legacy-plugin-chart-calendar/package.json
  plugins/legacy-plugin-chart-calendar/src/Calendar.css
  plugins/legacy-plugin-chart-calendar/src/Calendar.js
  plugins/legacy-plugin-chart-calendar/src/ReactCalendar.jsx
Labels: size/M

#572 chore(histogram): convert histogram css to emotion style
  plugins/legacy-plugin-chart-histogram/package.json
  plugins/legacy-plugin-chart-histogram/src/Histogram.css
  plugins/legacy-plugin-chart-histogram/src/Histogram.jsx
Labels: size/M

#597 feat: add color pallettes defined in SIP-34
  packages/superset-ui-color/src/colorSchemes/categorical/preset.ts
  packages/superset-ui-color/src/colorSchemes/categorical/superset.ts
  packages/superset-ui-color/src/colorSchemes/sequential/common.ts
  packages/superset-ui-color/test/colorSchemes.test.ts
  packages/superset-ui-demo/storybook/stories/superset-ui-color/ColorPallettesStories.jsx
Labels: size/L

#578 chore(chord chart): add emotion styling to chord chart
  plugins/legacy-plugin-chart-chord/package.json
  plugins/legacy-plugin-chart-chord/src/Chord.css
  plugins/legacy-plugin-chart-chord/src/Chord.js
  plugins/legacy-plugin-chart-chord/src/ReactChord.jsx
Labels: size/M

#595 feat(control-utils): better typing for control configs
  packages/superset-ui-control-utils/package.json
  packages/superset-ui-control-utils/src/ColumnOption.tsx
  packages/superset-ui-control-utils/src/index.ts
  packages/superset-ui-control-utils/src/shared-controls.tsx
  packages/superset-ui-control-utils/src/types.ts
  plugins/legacy-plugin-chart-table/src/controlPanel.tsx
  plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx
  plugins/legacy-preset-chart-big-number/src/sharedControls.ts
Labels: size/XXL

#592 chore(legacy-plugin-chart-calendar): use domains from control
  plugins/legacy-plugin-chart-calendar/src/Calendar.js
  plugins/legacy-plugin-chart-calendar/src/transformProps.js
Labels: size/S

#596 build: fix typing rebuild for single packages
  package.json
  scripts/build.js
Labels: size/S

#600 build: optimize storybook config
  packages/superset-ui-demo/.storybook/main.js
Labels: size/S

#601 feat: import theme colors
  packages/superset-ui-demo/storybook/stories/superset-ui-style/ThemeStories.jsx
  packages/superset-ui-style/src/index.ts
Labels: size/M

#613 chore: upgrade @types/react
  packages/superset-ui-chart-composition/package.json
  packages/superset-ui-chart/package.json
  plugins/legacy-plugin-chart-table/package.json
  plugins/plugin-chart-word-cloud/package.json
  temporary-plugins/package.json
  temporary-plugins/superset-ui-plugins-demo/package.json
  yarn.lock
Labels: size/S

#615 fix: pointing nvd3 package to nvd3-fork
  plugins/legacy-preset-chart-nvd3/package.json
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
Labels: size/XS

#619 build: bump @types/react to 16.9.38
  package.json
  packages/superset-ui-chart-composition/package.json
  packages/superset-ui-chart/package.json
  plugins/plugin-chart-choropleth-map/package.json
  plugins/plugin-chart-word-cloud/package.json
  temporary-plugins/package.json
  temporary-plugins/superset-ui-plugins-demo/package.json
  yarn.lock
Labels: size/M

#621 build: clean package-lock.json before release
  package.json
Labels: size/S

#622 build: update package versions in peerDependencies
  packages/superset-ui-chart-composition/package.json
  packages/superset-ui-chart-controls/package.json
  packages/superset-ui-chart/package.json
  packages/superset-ui-color/package.json
  packages/superset-ui-number-format/package.json
  packages/superset-ui-query/package.json
  packages/superset-ui-time-format/package.json
  packages/superset-ui-validator/package.json
  plugins/legacy-plugin-chart-calendar/package.json
  plugins/legacy-plugin-chart-chord/package.json
  plugins/legacy-plugin-chart-country-map/package.json
  plugins/legacy-plugin-chart-event-flow/package.json
  plugins/legacy-plugin-chart-force-directed/package.json
  plugins/legacy-plugin-chart-heatmap/package.json
  plugins/legacy-plugin-chart-histogram/package.json
  plugins/legacy-plugin-chart-horizon/package.json
  plugins/legacy-plugin-chart-iframe/package.json
  plugins/legacy-plugin-chart-map-box/package.json
  plugins/legacy-plugin-chart-markup/package.json
  plugins/legacy-plugin-chart-paired-t-test/package.json
  plugins/legacy-plugin-chart-parallel-coordinates/package.json
  plugins/legacy-plugin-chart-partition/package.json
  plugins/legacy-plugin-chart-pivot-table/package.json
  plugins/legacy-plugin-chart-rose/package.json
  plugins/legacy-plugin-chart-sankey-loop/package.json
  plugins/legacy-plugin-chart-sankey/package.json
  plugins/legacy-plugin-chart-sunburst/package.json
  plugins/legacy-plugin-chart-table/package.json
  plugins/legacy-plugin-chart-treemap/package.json
  plugins/legacy-plugin-chart-world-map/package.json
  plugins/legacy-preset-chart-big-number/package.json
  plugins/legacy-preset-chart-nvd3/package.json
  plugins/plugin-chart-choropleth-map/package.json
  plugins/plugin-chart-word-cloud/README.md
  plugins/plugin-chart-word-cloud/package.json
  plugins/preset-chart-xy/package.json
  temporary-plugins/hold-potentially-deprecate/superset-ui-legacy-plugin-chart-word-cloud/package.json
  temporary-plugins/hold-potentially-deprecate/superset-ui-plugin-chart-table/package.json
  temporary-plugins/package.json
  temporary-plugins/superset-ui-plugins-demo/package.json
Labels: size/L

#624 fix: got one color wrong when copy pasting
  packages/superset-ui-color/src/colorSchemes/categorical/superset.ts
Labels: size/XS

#628 chore(legacy-plugin-chart-country-map): use peerDependencies
  plugins/legacy-plugin-chart-country-map/package.json
Labels: size/XS

#632 feat(style): add opacity and zIndex variables to theme
  packages/superset-ui-style/src/index.ts
Labels: size/S

#633 chore: upgrade react-table to v7.2.1
  plugins/plugin-chart-table/package.json
  yarn.lock
Labels: size/S
