Repository apache-superset/superset-ui, pull requests merged in 2020-02, with the labels that each got.

#289 build: fix lints
  package.json
  packages/superset-ui-chart/test/components/ChartDataProvider.test.tsx
  packages/superset-ui-chart/test/components/createLoadableRenderer.test.tsx
  packages/superset-ui-chart/test/components/reactify.test.tsx
  packages/superset-ui-chart/test/index.test.ts
  packages/superset-ui-connection/test/callApi/callApiAndParseWithTimeout.test.ts
  packages/superset-ui-connection/test/callApi/rejectAfterTimeout.test.ts
  packages/superset-ui-core/test/models/ExtensibleFunction.test.js
  packages/superset-ui-core/test/models/ExtensibleFunction.test.ts
  packages/superset-ui-number-format/test/NumberFormatter.test.js
  packages/superset-ui-number-format/test/NumberFormatter.test.ts
Labels: reviewable

#290 build: rename yarn type:dts to yarn type
  package.json
Labels: size/XS

#291 build: remove babel transform runtime
  package.json
  packages/superset-ui-core/package.json
Labels: size/XS

#292 Update frontend assets path in debugging doc
  docs/debugging.md
Labels: size/XS

#298 build: fix demo build
  .gitignore
  packages/superset-ui-demo/.storybook/webpack.config.js
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/stories/index.js
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/ChartDataProviderStories.tsx
  yarn.lock
Labels: size/M
