Repository apache-superset/superset-ui, pull requests merged in 2020-09, with the labels that each got.

#761 fix(style): throw if there is no theme
  packages/superset-ui-style/package.json
  packages/superset-ui-style/src/index.ts
  packages/superset-ui-style/test/index.test.ts
  packages/superset-ui-style/test/index.test.tsx
Labels: size/M

#764 fix: add Echarts tooltip confine
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
Labels: size/XS

#767 fix(legacy-preset-chart-nvd3): remove unnecessary control override
  plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts
Labels: size/XS

#775 chore: url prop for MetricOption should be optional
  packages/superset-ui-chart-controls/src/components/MetricOption.tsx
Labels: size/XS

#774 chore: move @types/react to peerDependencies
  packages/superset-ui-chart-controls/package.json
  packages/superset-ui-core/package.json
  packages/superset-ui-demo/package.json
  plugins/legacy-plugin-chart-time-table/package.json
  plugins/plugin-chart-choropleth-map/package.json
  plugins/plugin-chart-table/package.json
  plugins/plugin-chart-word-cloud/package.json
  yarn.lock
Labels: size/M

#769 build: enable skipLibCheck for tsc
  package.json
  plugins/legacy-plugin-chart-calendar/tsconfig.json
  plugins/legacy-plugin-chart-chord/tsconfig.json
  plugins/legacy-plugin-chart-country-map/tsconfig.json
  plugins/legacy-plugin-chart-event-flow/tsconfig.json
  plugins/legacy-plugin-chart-force-directed/tsconfig.json
  plugins/legacy-plugin-chart-heatmap/tsconfig.json
  plugins/legacy-plugin-chart-histogram/tsconfig.json
  plugins/legacy-plugin-chart-horizon/tsconfig.json
  plugins/legacy-plugin-chart-map-box/tsconfig.json
  plugins/legacy-plugin-chart-paired-t-test/tsconfig.json
  plugins/legacy-plugin-chart-parallel-coordinates/tsconfig.json
  plugins/legacy-plugin-chart-partition/tsconfig.json
  plugins/legacy-plugin-chart-pivot-table/tsconfig.json
  plugins/legacy-plugin-chart-rose/tsconfig.json
  plugins/legacy-plugin-chart-sankey-loop/tsconfig.json
  plugins/legacy-plugin-chart-sankey/tsconfig.json
  plugins/legacy-plugin-chart-sunburst/tsconfig.json
  plugins/legacy-plugin-chart-time-table/tsconfig.json
  plugins/legacy-plugin-chart-treemap/tsconfig.json
  plugins/legacy-plugin-chart-world-map/tsconfig.json
  plugins/legacy-preset-chart-big-number/tsconfig.json
  plugins/legacy-preset-chart-nvd3/tsconfig.json
  plugins/plugin-chart-choropleth-map/tsconfig.json
  plugins/plugin-chart-echarts/tsconfig.json
  plugins/plugin-chart-table/tsconfig.json
  plugins/plugin-chart-word-cloud/tsconfig.json
  plugins/preset-chart-xy/tsconfig.json
  scripts/build.js
  tsconfig.options.json
Labels: size/L

#771 refactor: convert legacy-plugin-chart-event-flow to typescript
  packages/superset-ui-chart-controls/src/utils/columnChoices.ts
  packages/superset-ui-core/src/chart/types/QueryResponse.ts
  plugins/legacy-plugin-chart-event-flow/src/EventFlow.tsx
  plugins/legacy-plugin-chart-event-flow/src/controlPanel.tsx
  plugins/legacy-plugin-chart-event-flow/src/index.ts
  plugins/legacy-plugin-chart-event-flow/src/transformProps.ts
  plugins/legacy-plugin-chart-event-flow/src/types/external.d.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
  plugins/plugin-chart-echarts/src/utils/prophet.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
Labels: size/L

#776 fix: add back nvd3 missing css
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
Labels: size/XS

#779 chore: move all superset-ui/core deps out of peerDependencies
  plugins/legacy-plugin-chart-calendar/package.json
  plugins/legacy-plugin-chart-event-flow/package.json
  plugins/legacy-plugin-chart-rose/package.json
  plugins/plugin-chart-echarts/package.json
Labels: size/S

#777 feat: make GET request work for fetchExploreJson, closes #668
  packages/superset-ui-core/src/query/api/legacy/fetchExploreJson.ts
  packages/superset-ui-core/test/query/api/legacy/fetchExploreJson.test.ts
Labels: size/M

#782 fix: update lineMulti when queryData changes
  plugins/legacy-preset-chart-nvd3/src/LineMulti/LineMulti.jsx
Labels: size/XS

#787 feat(plugin-chart-echarts): remove loading from timeseries tooltip
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
Labels: size/XS

#786 chore: add more props to DatasourceMeta for chart-controls
  packages/superset-ui-chart-controls/src/types.ts
Labels: size/S

#788 fix(plugin-chart-word-cloud): make colors schemes work
  plugins/plugin-chart-word-cloud/src/plugin/index.ts
  plugins/preset-chart-xy/src/BoxPlot/index.ts
Labels: size/XS

#783 feat(plugin-chart-echarts): add more robust formatting for series
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/constants.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
  plugins/plugin-chart-echarts/test/utils/series.test.ts
Labels: size/L

#800 fix(plugin-chart-echarts): fix incorrect groupby in buildQuery
  plugins/plugin-chart-echarts/src/Timeseries/buildQuery.ts
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.ts
  plugins/plugin-chart-echarts/test/Timeseries/buildQuery.test.ts
  plugins/plugin-chart-echarts/test/Timeseries/transformProps.test.ts
Labels: size/S
