Repository apache-superset/superset-ui, pull requests merged in 2020-03, with the labels that each got.

#305 feat: add NoResultsComponent to charts
  packages/superset-ui-chart/src/components/NoResultsComponent.tsx
  packages/superset-ui-chart/src/components/SuperChart.tsx
  packages/superset-ui-chart/test/components/NoResultsComponent.test.tsx
  packages/superset-ui-chart/test/components/SuperChart.test.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx
Labels: size/L

#307 feat: make formatTime and formatNumber accept undefined type
  packages/superset-ui-number-format/src/NumberFormatterRegistry.ts
  packages/superset-ui-number-format/test/NumberFormatterRegistry.test.ts
  packages/superset-ui-time-format/src/TimeFormatterRegistry.ts
  packages/superset-ui-time-format/test/TimeFormatterRegistry.test.ts
Labels: size/S

#308 feat: add more support for undefined format to number and time formatters
  packages/superset-ui-number-format/src/NumberFormatterRegistry.ts
  packages/superset-ui-number-format/src/NumberFormatterRegistrySingleton.ts
  packages/superset-ui-number-format/test/NumberFormatterRegistry.test.ts
  packages/superset-ui-number-format/test/NumberFormatterRegistrySingleton.test.ts
  packages/superset-ui-time-format/src/TimeFormatterRegistry.ts
  packages/superset-ui-time-format/src/TimeFormatterRegistrySingleton.ts
  packages/superset-ui-time-format/test/TimeFormatterRegistry.test.ts
  packages/superset-ui-time-format/test/TimeFormatterRegistrySingleton.test.ts
Labels: size/M

#309 fix: small rendering for no results message
  packages/superset-ui-chart/src/components/NoResultsComponent.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx
Labels: size/M
