Repository apache-superset/superset-ui, pull requests merged in 2020-12, with the labels that each got.

#846 feat: support multi queries request
  packages/superset-ui-core/src/chart/components/SuperChart.tsx
  packages/superset-ui-core/src/chart/models/ChartProps.ts
  packages/superset-ui-core/test/chart/components/SuperChart.test.tsx
Labels: size/L

#850 fix(legacy-preset-chart-nvd3): time compare and stacked area tooltips
  packages/superset-ui-demo/storybook/stories/plugins/legacy-preset-chart-nvd3/Compare/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/legacy-preset-chart-nvd3/Compare/stories/timeFormat.tsx
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/legacy-preset-chart-nvd3/src/utils.js
  yarn.lock
Labels: size/L

#836 refactor: Relocating/renaming various chart controls
  packages/superset-ui-chart-controls/src/sections.tsx
  packages/superset-ui-chart-controls/src/types.ts
  packages/superset-ui-core/src/color/CategoricalColorScale.ts
  packages/superset-ui-core/src/color/SequentialScheme.ts
  plugins/legacy-plugin-chart-calendar/src/controlPanel.js
  plugins/legacy-plugin-chart-country-map/src/controlPanel.ts
  plugins/legacy-plugin-chart-event-flow/src/controlPanel.tsx
  plugins/legacy-plugin-chart-force-directed/src/controlPanel.js
  plugins/legacy-plugin-chart-heatmap/src/controlPanel.js
  plugins/legacy-plugin-chart-histogram/src/controlPanel.js
  plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts
  plugins/legacy-plugin-chart-partition/src/controlPanel.jsx
  plugins/legacy-plugin-chart-treemap/src/controlPanel.js
  plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bubble/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
Labels: size/M

#851 fix(demo): add antd css and implement action hook on select filter story
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/stories/plugins/plugin-filter-antd/Select/Stories.tsx
  plugins/plugin-filter-antd/src/Select/AntdSelectFilter.tsx
  plugins/plugin-filter-antd/src/Select/transformProps.ts
Labels: size/S

#852 feat(plugin-chart-echarts): bump to version 5.0
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Pie/Stories.tsx
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Pie/controlPanel.ts
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/components/Echart.tsx
  yarn.lock
Labels: size/M

#853 ci: remove `pull_request` trigger
  .github/workflows/chromatic.yml
Labels: size/XS

#855 fix(legacy-preset-chart-nvd3): make deep copy of queryData
  plugins/legacy-preset-chart-nvd3/src/LineMulti/LineMulti.jsx
Labels: size/XS

#863 fix(legacy-plugin-chart-histogram): fixes legend overflow
  plugins/legacy-plugin-chart-histogram/src/Histogram.jsx
  plugins/legacy-plugin-chart-histogram/src/WithLegend.jsx
Labels: size/S

#867 fix: add fetchRetryOptions in SupersetClientClass.request method
  packages/superset-ui-core/src/connection/SupersetClientClass.ts
Labels: size/XS

#869 chore(chart-controls): remove dedicated time section
  packages/superset-ui-chart-controls/src/sections.tsx
  packages/superset-ui-chart-controls/src/types.ts
  packages/superset-ui-chart-controls/src/utils/columnChoices.ts
  packages/superset-ui-chart-controls/test/utils/columnChoices.test.tsx
  plugins/legacy-plugin-chart-calendar/src/controlPanel.js
  plugins/legacy-plugin-chart-chord/src/controlPanel.js
  plugins/legacy-plugin-chart-country-map/src/controlPanel.ts
  plugins/legacy-plugin-chart-event-flow/src/controlPanel.tsx
  plugins/legacy-plugin-chart-force-directed/src/controlPanel.js
  plugins/legacy-plugin-chart-heatmap/src/controlPanel.js
  plugins/legacy-plugin-chart-histogram/src/controlPanel.js
  plugins/legacy-plugin-chart-horizon/src/controlPanel.js
  plugins/legacy-plugin-chart-map-box/src/controlPanel.js
  plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts
  plugins/legacy-plugin-chart-parallel-coordinates/src/controlPanel.ts
  plugins/legacy-plugin-chart-partition/src/controlPanel.jsx
  plugins/legacy-plugin-chart-pivot-table/src/controlPanel.js
  plugins/legacy-plugin-chart-rose/src/controlPanel.jsx
  plugins/legacy-plugin-chart-sankey-loop/src/controlPanel.js
  plugins/legacy-plugin-chart-sankey/src/controlPanel.ts
  plugins/legacy-plugin-chart-sunburst/src/controlPanel.ts
  plugins/legacy-plugin-chart-time-table/src/controlPanel.ts
  plugins/legacy-plugin-chart-treemap/src/controlPanel.js
  plugins/legacy-plugin-chart-world-map/src/controlPanel.js
  plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx
  plugins/legacy-preset-chart-big-number/src/BigNumberTotal/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bubble/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bullet/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Compare/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Line/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
  plugins/legacy-preset-chart-nvd3/src/Pie/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/TimePivot/controlPanel.ts
  plugins/plugin-chart-echarts/src/BoxPlot/controlPanel.ts
  plugins/plugin-chart-echarts/src/Pie/controlPanel.ts
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-table/src/controlPanel.tsx
  plugins/plugin-chart-word-cloud/src/plugin/controlPanel.ts
  plugins/plugin-filter-antd/src/Range/controlPanel.ts
  plugins/plugin-filter-antd/src/Select/controlPanel.ts
  plugins/preset-chart-xy/src/BoxPlot/controlPanel.ts
Labels: size/L

#864 test: disable Chromatic for VerifyCORS
  packages/superset-ui-demo/storybook/shared/components/createQueryStory.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-choropleth-map/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/birthNames.json
  packages/superset-ui-demo/storybook/stories/superset-ui-connection/ConnectionStories.tsx
Labels: size/S
