Repository apache-superset/superset-ui, pull requests merged in 2021-06, with the labels that each got.

#1142 feat: adding to feature flag enum
  packages/superset-ui-core/src/utils/featureFlags.ts
Labels: size/XS

#1143 fix(plugin-chart-echarts): fix tooltip format in mixed ts chart
  plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
Labels: size/S

#1145 fix: changed FORCE_SSL to FORCE_DATABASE_CONNECTIONS_SSL
  packages/superset-ui-core/src/utils/featureFlags.ts
Labels: size/XS

#1156 fix(plugin-chart-echarts): order by timeseries limit metric
  plugins/plugin-chart-echarts/src/MixedTimeseries/buildQuery.ts
  plugins/plugin-chart-echarts/src/Timeseries/buildQuery.ts
  plugins/plugin-chart-echarts/test/Timeseries/buildQuery.test.ts
Labels: size/M

#1149 chore(core): add new fields to metadata class
  packages/superset-ui-core/src/chart/models/ChartMetadata.ts
Labels: size/M

#1162 fix: tooltips on nvd3 charts
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
Labels: size/S

#1159 chore(plugin-chart-echarts): bump echarts to 5.1.2
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Tree/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Treemap/EchartsTreemap.tsx
  plugins/plugin-chart-echarts/src/components/Echart.tsx
Labels: size/S

#1172 feat(plugin-chart-pivot-table): enable metrics to be used as row groups
  plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
  plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
  plugins/plugin-chart-pivot-table/src/plugin/transformProps.ts
  plugins/plugin-chart-pivot-table/src/types.ts
  plugins/plugin-chart-pivot-table/test/plugin/transformProps.test.ts
Labels: size/M

#1176 fix(core): remove height and width requirement on SuperChart
  packages/superset-ui-core/src/chart/components/SuperChart.tsx
Labels: size/XS

#1151 fix(plugin-chart-echarts): [treemap v2] fix the section color and disabling the zoom on the explore
  plugins/plugin-chart-echarts/src/Treemap/constants.ts
  plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
Labels: size/XS

#1177 chore(core): adjustments to chart metadata
  packages/superset-ui-core/src/chart/models/ChartMetadata.ts
Labels: size/S

#1180 fix(plugin-chart-echarts): radar legend control is duplicated
  plugins/plugin-chart-echarts/src/Radar/controlPanel.tsx
Labels: size/XS

#1144 fix(core): missing translation
  packages/superset-ui-core/src/chart/components/NoResultsComponent.tsx
  packages/superset-ui-core/test/chart/components/NoResultsComponent.test.tsx
Labels: size/S

#1182 fix(plugin-chart-echarts): tree graph tooltip polish
  plugins/plugin-chart-echarts/src/Tree/transformProps.ts
Labels: size/S

#1189 fix(plugin-chart-table): chinesee translation improve
  plugins/plugin-chart-table/src/i18n.ts
Labels: size/XS

#1187 fix(plugin-chart-echarts): [time-series][mixed timeseries] marker control does not work
  plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
Labels: size/S

#1191 feat(core): Registry listeners
  packages/superset-ui-core/src/models/Registry.ts
  packages/superset-ui-core/test/models/Registry.test.ts
Labels: size/L
