Repository apache-superset/superset-ui, pull requests merged in 2021-01, with the labels that each got.

#886 fix(core): handle missing where in appendExtraFormData
  packages/superset-ui-core/src/query/processExtraFormData.ts
  packages/superset-ui-core/test/query/processExtraFormData.test.ts
Labels: size/S

#884 ci: switch chromatic action to workflow_run
  .github/workflows/chromatic.yml
  .github/workflows/ci.yml
Labels: size/M

#891 chore: bumping nvd3-fork package
  plugins/legacy-preset-chart-nvd3/package.json
  yarn.lock
Labels: size/S

#890 chore: update layout control for rolling window
  plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
Labels: size/XS

#880 fix(legacy-plugin-chart-pivot-table): pivot table chart string aggregation empty values
  plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
  plugins/legacy-plugin-chart-pivot-table/src/utils/formatCells.ts
  plugins/legacy-plugin-chart-pivot-table/test/PivotTable.test.ts
Labels: size/L

#841 fix(plugin-chart-word-cloud): ensure top results are always displayed
  plugins/plugin-chart-word-cloud/src/chart/WordCloud.tsx
Labels: size/M

#892 chore: upgrade eslint and babel
  .github/workflows/chromatic.yml
  package.json
  packages/superset-ui-chart-controls/src/components/MetricOption.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-core/src/chart/clients/ChartClient.ts
  packages/superset-ui-core/src/dynamic-plugins/shared-modules.ts
  packages/superset-ui-core/src/models/Registry.ts
  packages/superset-ui-core/test/chart/components/ChartDataProvider.test.tsx
  packages/superset-ui-core/test/chart/components/createLoadableRenderer.test.tsx
  packages/superset-ui-core/test/chart/components/reactify.test.tsx
  packages/superset-ui-core/test/connection/SupersetClientClass.test.ts
  packages/superset-ui-core/test/connection/callApi/callApi.test.ts
  packages/superset-ui-core/test/connection/callApi/callApiAndParseWithTimeout.test.ts
  packages/superset-ui-core/test/connection/callApi/parseResponse.test.ts
  packages/superset-ui-core/test/connection/callApi/rejectAfterTimeout.test.ts
  packages/superset-ui-core/test/query/api/v1/makeApi.test.ts
  packages/superset-ui-core/test/time-format/factories/createD3TimeFormatter.test.ts
  plugins/legacy-plugin-chart-calendar/src/ReactCalendar.jsx
  plugins/legacy-plugin-chart-chord/src/ReactChord.jsx
  plugins/legacy-plugin-chart-force-directed/src/ReactForceDirected.jsx
  plugins/legacy-plugin-chart-parallel-coordinates/src/ReactParallelCoordinates.jsx
  plugins/legacy-plugin-chart-sankey/src/ReactSankey.jsx
  plugins/legacy-plugin-chart-world-map/src/ReactWorldMap.jsx
  plugins/legacy-preset-chart-nvd3/src/ReactNVD3.jsx
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/utils/annotation.ts
  plugins/plugin-chart-table/src/DataTable/DataTable.tsx
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/src/controlPanel.tsx
  plugins/plugin-chart-word-cloud/src/plugin/buildQuery.ts
  plugins/plugin-filter-antd/src/Range/buildQuery.ts
  plugins/plugin-filter-antd/src/Select/buildQuery.ts
  yarn.lock
Labels: size/XL

#901 fix(plugin-chart-echarts): remove columns from formData
  plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
  plugins/plugin-chart-echarts/test/BoxPlot/buildQuery.test.ts
Labels: size/XS

#900 fix: subject Remove margin to fit last label
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
Labels: size/XS

#896 chore: Update big number control options
  plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx
Labels: size/XS

#903 fix: subject Add width auto and enable scroll for big charts
  plugins/legacy-preset-chart-nvd3/src/ReactNVD3.jsx
Labels: size/XS

#894 feat(plugin-chart-echarts): Add xAxis label format && showMin and showMax labels
  .eslintrc.js
  packages/superset-ui-chart-controls/src/index.ts
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-chart-controls/src/types.ts
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
Labels: size/M

#904 feat(legacy-preset-chart-nvd3): subject Add legend option to dual line chart
  plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
Labels: size/S

#905 feat(legacy-plugin-chart-histogram): subject Add legend option to histogram chart
  plugins/legacy-plugin-chart-heatmap/src/controlPanel.ts
  plugins/legacy-plugin-chart-histogram/src/Histogram.jsx
  plugins/legacy-plugin-chart-histogram/src/controlPanel.ts
  plugins/legacy-plugin-chart-histogram/src/transformProps.js
Labels: size/M

#833 feat(plugin-chart-echarts): add legend customization options
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Pie/Stories.tsx
  plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/Pie/types.ts
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
  plugins/plugin-chart-echarts/src/controls.ts
  plugins/plugin-chart-echarts/src/defaults.ts
  plugins/plugin-chart-echarts/src/types.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
  plugins/plugin-chart-echarts/test/Pie/transformProps.test.ts
  plugins/plugin-chart-echarts/test/utils/series.test.ts
Labels: size/XL

#899 fix(legacy-preset-chart-nvd3): remove data fetching from multiline chart
  plugins/legacy-preset-chart-nvd3/src/LineMulti/LineMulti.jsx
  plugins/legacy-preset-chart-nvd3/src/LineMulti/index.js
Labels: size/L

#913 chore: move all controls for NVD3 and Big Number charts to separate rows
  .gitignore
  plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx
  plugins/legacy-preset-chart-nvd3/src/Bar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Line/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
  plugins/legacy-preset-chart-nvd3/src/TimePivot/controlPanel.ts
Labels: size/L

#909 fix: remove max-width from tooltip div
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/legacy-preset-chart-nvd3/src/utils.js
Labels: size/XS

#908 feat(legacy-preset-chart-nvd3): subject Add Y bounds for nvd3 charts
  plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/legacy-preset-chart-nvd3/src/transformProps.js
Labels: size/M

#912 feat(plugin-chart-echarts): subject Add time formatter on the tooltip title
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
Labels: size/S

#906 feat(plugin-chart-echarts): subject Add rich tooltip
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
Labels: size/M

#919 feat(core): add orderby to extractQueryFields
  packages/superset-ui-core/src/query/buildQueryObject.ts
  packages/superset-ui-core/src/query/extractQueryFields.ts
  packages/superset-ui-core/src/query/types/Query.ts
  packages/superset-ui-core/src/query/types/QueryFormData.ts
  packages/superset-ui-core/test/query/extractQueryFields.test.ts
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/L

#914 fix(chart-controls): add a tooltip to span in ColumnOption, refactor RB Tooltips to Antd
  packages/superset-ui-chart-controls/package.json
  packages/superset-ui-chart-controls/src/components/ColumnOption.tsx
  packages/superset-ui-chart-controls/src/components/InfoTooltipWithTrigger.tsx
  packages/superset-ui-chart-controls/src/components/Tooltip.tsx
  packages/superset-ui-chart-controls/test/components/InfoTooltipWithTrigger.test.tsx
Labels: size/M
