Repository apache-superset/superset-ui, pull requests merged in 2021-11, with the labels that each got.

#1440 chore(plugin-chart-echarts): bump echarts to 5.2.2
  package-lock.json
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
Labels: size/XS

#1416 feat: Add Saudi Arabia country map
  plugins/legacy-plugin-chart-country-map/src/countries.ts
  plugins/legacy-plugin-chart-country-map/src/countries/saudi_arabia.geojson
Labels: size/XS

#1447 fix(plugin-chart-echarts): fix tick labels and tooltip
  plugins/plugin-chart-echarts/src/MixedTimeseries/EchartsMixedTimeseries.tsx
  plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/types.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
Labels: size/M

#1448 fix(plugin-chart-echarts): boxplot groupby incorrect
  packages/superset-ui-chart-controls/src/operators/boxplotOperator.ts
  packages/superset-ui-core/src/query/types/PostProcessing.ts
  packages/superset-ui-core/test/query/types/PostProcessing.test.ts
  plugins/plugin-chart-echarts/test/BoxPlot/buildQuery.test.ts
Labels: size/L

#1406 fix: Color consistency
  packages/superset-ui-chart-controls/src/sections/sections.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-chart-controls/src/types.ts
  packages/superset-ui-core/src/color/CategoricalColorNamespace.ts
  packages/superset-ui-core/src/color/CategoricalColorScale.ts
  packages/superset-ui-core/test/color/CategoricalColorNameSpace.test.ts
  plugins/legacy-plugin-chart-chord/src/controlPanel.ts
  plugins/legacy-plugin-chart-histogram/src/controlPanel.ts
  plugins/legacy-plugin-chart-partition/src/controlPanel.tsx
  plugins/legacy-plugin-chart-rose/src/controlPanel.tsx
  plugins/legacy-plugin-chart-sankey-loop/src/controlPanel.ts
  plugins/legacy-plugin-chart-sankey/src/controlPanel.ts
  plugins/legacy-plugin-chart-treemap/src/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Area/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bubble/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Compare/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Line/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/LineMulti/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Pie/controlPanel.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Area/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Scatter/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Regular/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Step/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-word-cloud/src/plugin/controlPanel.ts
  plugins/preset-chart-xy/src/BoxPlot/controlPanel.ts
Labels: size/L

#1451 chore: update lockfile
  package-lock.json
  package.json
  packages/superset-ui-core/test/color/CategoricalColorNameSpace.test.ts
  scripts/build.js
Labels: size/XS

#1454 chore: check node and npm version in release workflow
  package-lock.json
  package.json
  scripts/lernaVersion.sh
Labels: size/S

#1449 feat(plugin-chart-echarts): support show annotation label [ID-8]
  packages/superset-ui-core/src/query/types/AnnotationLayer.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
Labels: size/M

#1452 feat(legacy-plugin-chart-calendar): increase the contrast of calendar heatmap color and label
  packages/superset-ui-core/src/color/index.ts
  packages/superset-ui-core/src/color/utils.ts
  packages/superset-ui-core/test/color/utils.test.ts
  plugins/legacy-plugin-chart-calendar/src/vendor/cal-heatmap.css
  plugins/legacy-plugin-chart-calendar/src/vendor/cal-heatmap.js
Labels: size/L

#1413 feat: Set default for Accept field in header to take application/json
  packages/superset-ui-core/src/connection/SupersetClientClass.ts
  packages/superset-ui-core/test/connection/SupersetClient.test.ts
Labels: size/S

#1460 chore: tweak unittest
  packages/superset-ui-core/test/query/buildQueryObject.test.ts
  packages/superset-ui-core/test/query/extractTimegrain.test.ts
  packages/superset-ui-core/test/query/types/AnnotationLayer.test.ts
  packages/superset-ui-core/test/time-format/formatters/smartDateDetailed.test.ts
  plugins/plugin-chart-echarts/src/index.ts
  plugins/plugin-chart-echarts/src/types.ts
  plugins/plugin-chart-echarts/test/utils/series.test.ts
Labels: size/S

#1459 chore: merge tsconfig.json and tsconfig.options.json
  packages/generator-superset/generators/plugin-chart/templates/tsconfig.json
  packages/generator-superset/test/tsconfig.json
  packages/superset-ui-chart-controls/test/tsconfig.json
  packages/superset-ui-chart-controls/tsconfig.json
  packages/superset-ui-core/test/tsconfig.json
  packages/superset-ui-core/tsconfig.json
  plugins/legacy-plugin-chart-calendar/tsconfig.json
  plugins/legacy-plugin-chart-chord/tsconfig.json
  plugins/legacy-plugin-chart-country-map/tsconfig.json
  plugins/legacy-plugin-chart-event-flow/tsconfig.json
  plugins/legacy-plugin-chart-force-directed/tsconfig.json
  plugins/legacy-plugin-chart-heatmap/tsconfig.json
  plugins/legacy-plugin-chart-histogram/tsconfig.json
  plugins/legacy-plugin-chart-horizon/tsconfig.json
  plugins/legacy-plugin-chart-map-box/test/tsconfig.json
  plugins/legacy-plugin-chart-map-box/tsconfig.json
  plugins/legacy-plugin-chart-paired-t-test/tsconfig.json
  plugins/legacy-plugin-chart-parallel-coordinates/tsconfig.json
  plugins/legacy-plugin-chart-partition/test/tsconfig.json
  plugins/legacy-plugin-chart-partition/tsconfig.json
  plugins/legacy-plugin-chart-pivot-table/tsconfig.json
  plugins/legacy-plugin-chart-rose/tsconfig.json
  plugins/legacy-plugin-chart-sankey-loop/tsconfig.json
  plugins/legacy-plugin-chart-sankey/tsconfig.json
  plugins/legacy-plugin-chart-sunburst/tsconfig.json
  plugins/legacy-plugin-chart-time-table/tsconfig.json
  plugins/legacy-plugin-chart-treemap/tsconfig.json
  plugins/legacy-plugin-chart-world-map/tsconfig.json
  plugins/legacy-preset-chart-big-number/test/tsconfig.json
  plugins/legacy-preset-chart-big-number/tsconfig.json
  plugins/legacy-preset-chart-nvd3/test/tsconfig.json
  plugins/legacy-preset-chart-nvd3/tsconfig.json
  plugins/plugin-chart-echarts/test/tsconfig.json
  plugins/plugin-chart-echarts/tsconfig.json
  plugins/plugin-chart-pivot-table/tsconfig.json
  plugins/plugin-chart-table/test/tsconfig.json
  plugins/plugin-chart-table/tsconfig.json
  plugins/plugin-chart-word-cloud/test/tsconfig.json
  plugins/plugin-chart-word-cloud/tsconfig.json
  plugins/preset-chart-xy/test/tsconfig.json
  plugins/preset-chart-xy/tsconfig.json
  temporary-plugins/plugin-chart-choropleth-map/test/tsconfig.json
  temporary-plugins/plugin-chart-choropleth-map/tsconfig.json
  tsconfig.eslint.json
  tsconfig.json
  tsconfig.options.json
Labels: size/L

#1457 chore: bump @typescript-eslint/eslint-plugin 5.3.0
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  packages/superset-ui-demo/.eslintrc
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/BoxPlot/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Funnel/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Gauge/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Graph/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Pie/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Radar/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Tree/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Treemap/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/preset-chart-xy/Line/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/preset-chart-xy/ScatterPlot/Stories.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-chart/SuperChartStories.tsx
  packages/superset-ui-demo/storybook/stories/superset-ui-style/ThemeStories.jsx
Labels: size/L

#1450 feat: remove the default Y-axis truncate in bar chart
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
Labels: size/L

#1464 fix(plugin-chart-echarts): fix opacity on area chart
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
Labels: size/S

#1462 fix: update chart sorting control labels/descriptions
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
Labels: size/M

#1466 chore: coordinate storybook with main repository
  package-lock.json
  packages/superset-ui-demo/package.json
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-chord/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-country-map/CountryMapStories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/BoxPlot/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Funnel/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Gauge/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Graph/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/MixedTimeseries/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Pie/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Radar/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Timeseries/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Tree/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Treemap/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/TableStories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-word-cloud/Stories.tsx
  packages/superset-ui-demo/tsconfig.json
  plugins/legacy-plugin-chart-country-map/src/index.js
  plugins/plugin-chart-echarts/src/index.ts
  plugins/plugin-chart-word-cloud/src/index.ts
Labels: size/L

#1465 fix(plugin-chart-pivot-table): cross filtering by adhoc column
  plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
Labels: size/S

#1467 chore: Pass dashboardId to ColorSchemeControl
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
Labels: size/XS

#1470 fix(plugin-chart-echarts): fix legend margin in radar and timeseries echart
  plugins/plugin-chart-echarts/src/Radar/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
Labels: size/XS
