Repository apache-superset/superset-ui, pull requests merged in 2021-08, with the labels that each got.

#1255 chore: add echarts tag for pie and radar
  plugins/plugin-chart-echarts/src/Pie/index.ts
  plugins/plugin-chart-echarts/src/Radar/index.ts
Labels: size/XS

#1256 feat(plugin-chart-echarts): implement cross filter in mixd-timeseries chart
  plugins/plugin-chart-echarts/src/MixedTimeseries/EchartsMixedTimeseries.tsx
  plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/MixedTimeseries/index.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/types.ts
Labels: size/L

#1254 docs: update publishing instructions
  CONTRIBUTING.md
Labels: size/S

#1259 fix(legacy-preset-chart-nvd3): dual line dnd control missing
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  plugins/legacy-preset-chart-nvd3/src/DualLine/controlPanel.ts
Labels: size/S

#1260 fix(plugin-chart-echarts): missing dnd control in tree chart
  plugins/plugin-chart-echarts/src/Tree/controlPanel.tsx
Labels: size/XS

#1261 fix(plugin-chart-pivot-table): make date formatting clearable
  plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
Labels: size/XS

#1263 fix(legacy-plugin-chart-sunburst): move color scheme controls to own row
  plugins/legacy-plugin-chart-sunburst/src/controlPanel.ts
Labels: size/XS

#1157 feat(plugin-chart-table): added emit target name
  packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/ColumnConfigControl.tsx
  packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/constants.tsx
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/M

#1265 fix(plugin-chart-pivot-table): dont display nulls as 0
  plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
Labels: size/S

#1269 fix(plugin-chart-pivot-table): dont apply colors to subtotals
  plugins/plugin-chart-pivot-table/package.json
  plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
Labels: size/XS

#1270 fix(plugin-chart-echarts): fix null labels on pie and funnel charts
  plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/test/Funnel/transformProps.test.ts
  plugins/plugin-chart-echarts/test/Pie/transformProps.test.ts
Labels: size/M

#1271 chore: Show tooltip conditionally and pass ref down
  packages/superset-ui-chart-controls/src/components/ColumnOption.tsx
  packages/superset-ui-chart-controls/src/components/MetricOption.tsx
Labels: size/M

#1276 fix(legacy-preset-chart-nvd3): bar chart unexpected error
  plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
Labels: size/S

#1281 feat(plugin-chart-table): add support for temporal x-filter
  packages/superset-ui-core/src/query/types/Filter.ts
  packages/superset-ui-core/src/query/types/Query.ts
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/transformProps.ts
  plugins/plugin-chart-table/src/types.ts
  plugins/plugin-chart-table/src/utils/DateWithFormatter.ts
Labels: size/M

#1284 fix(chart-controls): lower minOpacity in conditional formatting
  packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts
  packages/superset-ui-chart-controls/test/utils/getColorFormatters.test.ts
Labels: size/M

#1285 chore: change Highly-used back to Popular
  plugins/legacy-plugin-chart-world-map/src/index.js
  plugins/legacy-preset-chart-big-number/src/BigNumber/index.ts
  plugins/legacy-preset-chart-big-number/src/BigNumberTotal/index.ts
  plugins/legacy-preset-chart-nvd3/src/DistBar/index.js
  plugins/plugin-chart-echarts/src/Pie/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/Area/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Line/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Scatter/index.ts
  plugins/plugin-chart-pivot-table/src/plugin/index.ts
Labels: size/S

#1258 feat(legacy-plugin-chart-country-map): added finland map
  plugins/legacy-plugin-chart-country-map/src/countries.ts
  plugins/legacy-plugin-chart-country-map/src/countries/finland.geojson
Labels: size/S

#1279 feat(plugin-chart-echarts): Add support for series values to ECharts timeseries charts
  plugins/plugin-chart-echarts/src/Timeseries/Area/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Area/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Line/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/Regular/SmoothLine/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/Regular/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Step/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Step/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
  plugins/plugin-chart-echarts/src/controls.tsx
Labels: size/L

#1268 feat(legacy-plugin-chart-country-map): add Australia geojson file
  plugins/legacy-plugin-chart-country-map/src/countries.ts
  plugins/legacy-plugin-chart-country-map/src/countries/australia.geojson
Labels: size/L

#1267 feat(legacy-plugin-chart-country-map): add austria map to country map charts
  plugins/legacy-plugin-chart-country-map/src/countries.ts
  plugins/legacy-plugin-chart-country-map/src/countries/austria.geojson
Labels: size/S

#1273 chore: stacks and sorts Histogram controls
  plugins/legacy-plugin-chart-histogram/src/controlPanel.ts
Labels: size/S

#1272 chore: stacks and sorts Heatmap controls
  plugins/legacy-plugin-chart-heatmap/src/controlPanel.ts
Labels: size/M

#1283 fix: Hide Safari default tooltip
  packages/superset-ui-chart-controls/package.json
  packages/superset-ui-chart-controls/src/components/Tooltip.tsx
Labels: size/S

#1282 fix: 0 indicator on radar viz
  plugins/plugin-chart-echarts/src/Radar/transformProps.ts
Labels: size/M

#1297 chore(core): add ENABLE_DND_WITH_CLICK_UX ff
  packages/superset-ui-core/src/utils/featureFlags.ts
Labels: size/XS

#1286 chore(plugin-chart-pivot-table): change fontsize and border colors
  plugins/plugin-chart-pivot-table/package.json
Labels: size/XS

#1278 feat(legacy-preset-chart-big-number): add timestamp above number
  plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.tsx
  plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx
  plugins/legacy-preset-chart-big-number/src/BigNumber/transformProps.ts
  plugins/legacy-preset-chart-big-number/test/transformProps.test.ts
Labels: size/L

#1300 chore: updating one metadata field
  plugins/plugin-chart-table/src/index.ts
Labels: size/XS

#1306 chore: removing errant label from two charts that don't have AA (but should)
  plugins/legacy-plugin-chart-time-table/src/index.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/index.ts
Labels: size/XS

#1302 fix(plugin-chart-echarts): fix Time-series line x-filtering not working when not rich tooltip
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
Labels: size/S

#1275 feat(chart-controls): d3 formatting with .2% #1274
  packages/superset-ui-chart-controls/src/utils/D3Formatting.ts
Labels: size/XS

#1311 chore: change ghost button text for dndcontrols
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
Labels: size/XS

#1304 feat(plugin-chart-echarts): rich tooltip in ts chart supports scroll and highlighted
  plugins/plugin-chart-echarts/src/MixedTimeseries/EchartsMixedTimeseries.tsx
  plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
Labels: size/M

#1315 fix(plugin-chart-table): apply correct date formatting for time grain
  plugins/plugin-chart-pivot-table/src/plugin/transformProps.ts
  plugins/plugin-chart-table/src/transformProps.ts
Labels: size/S

#1316 chore: add a note to the pivot plugin
  plugins/plugin-chart-pivot-table/README.md
  plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
Labels: size/XS

#1317 fix(chart-controls): temporal col placeholder for hybrid dnd
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
Labels: size/XS

#1321 fix(legacy-plugin-chart-country-map): fix broken map of Finland
  plugins/legacy-plugin-chart-country-map/src/countries/finland.geojson
Labels: size/M

#1320 fix: Improve big number time format UX
  plugins/legacy-preset-chart-big-number/src/BigNumber/controlPanel.tsx
Labels: size/S

#1313 feat(plugin-chart-echarts): add only_total control to ts chart
  plugins/plugin-chart-echarts/src/Timeseries/Area/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Regular/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Step/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
  plugins/plugin-chart-echarts/src/controls.tsx
Labels: size/L

#1323 fix(plugin-chart-echarts): improve marksize range
  plugins/plugin-chart-echarts/src/Timeseries/Area/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Regular/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Step/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
Labels: size/XS

#1327 feat(legacy-plugin-chart-country-map): add six new maps
  plugins/legacy-plugin-chart-country-map/scripts/Country Map GeoJSON Generator.ipynb
  plugins/legacy-plugin-chart-country-map/src/countries.ts
  plugins/legacy-plugin-chart-country-map/src/countries/denmark.geojson
  plugins/legacy-plugin-chart-country-map/src/countries/estonia.geojson
  plugins/legacy-plugin-chart-country-map/src/countries/iceland.geojson
  plugins/legacy-plugin-chart-country-map/src/countries/norway.geojson
  plugins/legacy-plugin-chart-country-map/src/countries/poland.geojson
  plugins/legacy-plugin-chart-country-map/src/countries/sweden.geojson
  plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
Labels: size/XXL

#1325 fix(plugin-chart-echarts): [scatter-plot] remove contribution mode
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Scatter/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Scatter/index.ts
Labels: size/L

#1310 fix: Make the scrollbar appear inside the table
  plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
Labels: size/M

#1335 chore: color schemes can be default theoretically
  packages/superset-ui-core/src/color/ColorScheme.ts
Labels: size/XS
