Repository apache-superset/superset-ui, pull requests merged in 2021-02, with the labels that each got.

#925 fix(plugin-chart-table): unnecessary post_processing in raw records mode
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/test/buildQuery.test.ts
Labels: size/L

#930 fix(plugin-chart-table): refine ordering logic
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/src/types.ts
  plugins/plugin-chart-table/src/utils/extractOrderby.ts
  plugins/plugin-chart-table/test/utils.test.ts
Labels: size/L

#935 fix(plugin-chart-table): always sort descending by first metric
  packages/superset-ui-core/src/query/buildQueryObject.ts
  packages/superset-ui-core/src/utils/ensureIsArray.ts
  packages/superset-ui-core/src/utils/index.ts
  packages/superset-ui-core/test/query/buildQueryObject.test.ts
  packages/superset-ui-core/test/utils/ensureIsArray.test.ts
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/L

#928 feat(plugin-chart-echarts): subject Update echarts to v5.0.1
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/BoxPlot/types.ts
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/components/Echart.tsx
  plugins/plugin-chart-echarts/src/types.ts
  plugins/plugin-chart-echarts/src/utils/annotation.ts
  plugins/plugin-chart-echarts/src/utils/prophet.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
Labels: size/L

#937 fix(plugin-chart-table): better rendering for temporal columns
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/src/transformProps.ts
  plugins/plugin-chart-table/src/types.ts
Labels: size/S

#942 fix(plugin-chart-echarts): label type and hover bugs
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
  yarn.lock
Labels: next-release, size/M

#921 feat(plugin-chart-echarts): subject Add option to rotate label defaul 45
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
Labels: size/S

#939 feat(plugin-chart-word-cloud): subject Add order by desc on metric
  plugins/plugin-chart-word-cloud/src/plugin/buildQuery.ts
  plugins/plugin-chart-word-cloud/src/plugin/controlPanel.ts
Labels: next-release, size/S

#946 feat(plugin-chart-echarts): subject add sort by metric for Pie Chart
  plugins/plugin-chart-echarts/src/Pie/buildQuery.ts
  plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
Labels: size/S

#929 feat(core): add custom_params to form_data
  packages/superset-ui-chart-controls/src/sections.tsx
  packages/superset-ui-core/src/query/buildQueryObject.ts
  packages/superset-ui-core/src/query/types/Query.ts
  packages/superset-ui-core/src/query/types/QueryFormData.ts
  packages/superset-ui-core/test/query/buildQueryObject.test.ts
Labels: size/S

#947 feat(legacy-preset-chart-nvd3): subject NVD3 Bar chart sort by
  plugins/legacy-preset-chart-nvd3/src/DistBar/controlPanel.ts
Labels: design-sys-revisit, size/S

#953 feat: Single metric sort
  plugins/legacy-plugin-chart-chord/src/controlPanel.ts
  plugins/legacy-plugin-chart-force-directed/src/controlPanel.ts
  plugins/legacy-plugin-chart-heatmap/src/controlPanel.ts
  plugins/legacy-plugin-chart-sunburst/src/controlPanel.ts
  plugins/legacy-plugin-chart-world-map/src/controlPanel.ts
Labels: size/M

#958 feat(plugin-chart-table): add tooltip about multiple sort
  plugins/plugin-chart-table/src/TableChart.tsx
Labels: design-sys-revisit, size/XS

#952 feat: add sort by metric for charts with multiple metrics
  plugins/legacy-plugin-chart-parallel-coordinates/src/controlPanel.ts
  plugins/legacy-plugin-chart-pivot-table/src/controlPanel.ts
  plugins/legacy-plugin-chart-treemap/src/controlPanel.ts
Labels: size/M

#956 fix(plugin-chart-echarts): fix Timeseries tooltip title
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
Labels: size/XS

#954 fix(legacy-plugin-chart-pivot-table): fix displaying image inside rows
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-pivot-table/Stories.tsx
  plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
  plugins/legacy-plugin-chart-pivot-table/src/utils/formatCells.ts
  plugins/legacy-plugin-chart-pivot-table/test/PivotTable.test.ts
  yarn.lock
Labels: size/L

#920 feat(plugin-chart-echarts): arrange legend and zoom
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/constants.ts
  plugins/plugin-chart-echarts/src/types.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
  plugins/plugin-chart-echarts/test/utils/series.test.ts
Labels: size/M

#961 fix(legacy-plugin-chart-paired-t-test): fix paired t-test table chart
  plugins/legacy-plugin-chart-paired-t-test/package.json
  plugins/legacy-plugin-chart-paired-t-test/src/PairedTTest.jsx
  plugins/legacy-plugin-chart-paired-t-test/src/TTestTable.jsx
  plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts
  plugins/legacy-plugin-chart-paired-t-test/src/transformProps.js
Labels: size/S

#965 fix(legacy-plugin-chart-map-box): fix downloading map as image
  plugins/legacy-plugin-chart-map-box/src/MapBox.jsx
Labels: size/XS

#960 feat(legacy-plugin-chart-map-box): show all points in mapbox chart
  plugins/legacy-plugin-chart-map-box/src/MapBox.jsx
Labels: size/S

#962 refactor(chart-controls): improve typing and file organization
  packages/superset-ui-chart-controls/src/components/InfoTooltipWithTrigger.tsx
  packages/superset-ui-chart-controls/src/components/MetricOption.tsx
  packages/superset-ui-chart-controls/src/components/Tooltip.tsx
  packages/superset-ui-chart-controls/src/index.ts
  packages/superset-ui-chart-controls/src/shared-controls/components/RadioButtonControl.tsx
  packages/superset-ui-chart-controls/src/shared-controls/components/index.tsx
  packages/superset-ui-chart-controls/src/types.ts
  packages/superset-ui-chart-controls/test/utils/expandControlConfig.test.tsx
  packages/superset-ui-core/src/chart/index.ts
  packages/superset-ui-core/src/chart/types/Base.ts
  packages/superset-ui-core/src/chart/types/QueryResponse.ts
  packages/superset-ui-core/src/chart/types/TransformFunction.ts
  packages/superset-ui-core/src/connection/index.ts
  packages/superset-ui-core/src/connection/types.ts
  packages/superset-ui-core/src/dimension/index.ts
  packages/superset-ui-core/src/dimension/types.ts
  packages/superset-ui-core/src/query/api/legacy/index.ts
  packages/superset-ui-core/src/query/api/legacy/types.ts
  packages/superset-ui-core/src/query/types/Column.ts
  packages/superset-ui-core/src/query/types/Datasource.ts
  packages/superset-ui-core/src/query/types/Metric.ts
  packages/superset-ui-core/src/query/types/Query.ts
  packages/superset-ui-core/src/query/types/QueryFormData.ts
  packages/superset-ui-core/src/query/types/QueryResponse.ts
  packages/superset-ui-core/src/query/types/Time.ts
  packages/superset-ui-core/src/query/types/index.ts
  packages/superset-ui-core/src/translation/index.ts
  packages/superset-ui-core/src/translation/types/index.ts
  packages/superset-ui-core/src/translation/types/jed.ts
  plugins/legacy-plugin-chart-time-table/src/TimeTable.tsx
Labels: size/L

#969 fix(chart-controls): expose datasource for some controls
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
Labels: size/XS

#970 chore: upgrade node to v14
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .nvmrc
  package.json
  yarn.lock
Labels: size/S

#967 feat: add dropGroupByControl
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-chart-controls/src/types.ts
Labels: size/M

#979 fix: remove duplicated group by field
  plugins/legacy-plugin-chart-paired-t-test/src/controlPanel.ts
Labels: size/S
