Repository apache-superset/superset-ui, pull requests merged in 2021-04, with the labels that each got.

#1036 fix(chart-controls): transform emotion css prop
  babel.config.js
  jest.config.js
  package.json
  packages/superset-ui-chart-controls/src/components/ControlForm/index.tsx
  packages/superset-ui-core/package.json
  scripts/build.js
  yarn.lock
Labels: size/L

#1021 feat: extra_jwt support to be used in dashboard_rbac
  packages/superset-ui-core/src/query/buildQueryContext.ts
  packages/superset-ui-core/src/query/types/Query.ts
  packages/superset-ui-core/src/query/types/QueryFormData.ts
  packages/superset-ui-core/src/utils/featureFlags.ts
  packages/superset-ui-core/test/query/buildQueryContext.test.ts
Labels: size/S

#1039 fix(plugin-chart-table): add text align to table header
  plugins/plugin-chart-table/src/TableChart.tsx
Labels: size/M

#1034 feat(plugin-chart-table): Implement showing totals
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  plugins/plugin-chart-table/package.json
  plugins/plugin-chart-table/src/DataTable/DataTable.tsx
  plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx
  plugins/plugin-chart-table/src/Styles.tsx
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/src/controlPanel.tsx
  plugins/plugin-chart-table/src/transformProps.ts
  plugins/plugin-chart-table/src/types.ts
  plugins/plugin-chart-table/src/utils/formatValue.ts
  yarn.lock
Labels: size/L

#1042 feat(feature-flag): add ALERTS_ATTACH_REPORTS feature flag
  packages/superset-ui-core/src/utils/featureFlags.ts
Labels: size/XS

#1038 feat(native-filters): add AppSection type
  packages/superset-ui-core/src/chart/models/ChartProps.ts
  packages/superset-ui-core/src/chart/types/Base.ts
Labels: size/S

#1041 feat(plugin-chart-table): enable emitting cross-filters
  plugins/plugin-chart-table/src/Styles.tsx
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/controlPanel.tsx
  plugins/plugin-chart-table/src/index.ts
  plugins/plugin-chart-table/src/transformProps.ts
Labels: size/M

#1047 fix(plugin-chart-table): fix empty metrics
  plugins/plugin-chart-table/src/buildQuery.ts
Labels: size/XS

#1044 fix(plugin-chart-echarts): fix unnecessary chart clearing
  plugins/plugin-chart-echarts/src/components/Echart.tsx
Labels: size/S

#1046 fix(plugin-chart-echarts): add series deduplication
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
  plugins/plugin-chart-echarts/test/utils/series.test.ts
Labels: size/M

#1043 fix(plugin-chart-echarts): default to standard x-axis format
  packages/superset-ui-chart-controls/src/utils/D3Formatting.ts
  packages/superset-ui-core/src/time-format/formatters/smartDateDetailed.ts
  packages/superset-ui-core/src/time-format/index.ts
  packages/superset-ui-core/test/time-format/formatters/smartDateDetailed.test.ts
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
Labels: size/L

#1049 fix(legacy-preset-chart-nvd3): fix tokenizer input type
  plugins/legacy-preset-chart-nvd3/src/utils/tokenize.ts
  plugins/legacy-preset-chart-nvd3/test/utils/tokenize.test.js
Labels: size/S

#1040 refactor(native-filters): Update `dataMask` structure
  packages/superset-ui-core/src/chart/models/ChartProps.ts
  packages/superset-ui-core/src/chart/registries/ChartBuildQueryRegistrySingleton.ts
  packages/superset-ui-core/src/chart/types/Base.ts
  packages/superset-ui-core/src/chart/types/TransformFunction.ts
  packages/superset-ui-core/src/query/buildQueryContext.ts
  plugins/plugin-chart-echarts/src/BoxPlot/EchartsBoxPlot.tsx
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/BoxPlot/types.ts
  plugins/plugin-chart-echarts/src/Pie/EchartsPie.tsx
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/Pie/types.ts
  plugins/plugin-chart-table/src/DataTable/utils/externalAPIs.ts
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/src/transformProps.ts
Labels: size/L

#1052 fix(plugin-chart-echarts): fix unnecessary highlight
  plugins/plugin-chart-echarts/src/components/Echart.tsx
Labels: size/S

#1051 chore(plugin-chart-table): Add muted attribute of video tag to whitelist
  plugins/plugin-chart-table/src/utils/formatValue.ts
Labels: size/XS

#1053 chore(core): simplify ExtraFormData
  packages/superset-ui-core/src/chart/types/Base.ts
  packages/superset-ui-core/src/query/buildQueryContext.ts
  packages/superset-ui-core/src/query/buildQueryObject.ts
  packages/superset-ui-core/src/query/constants.ts
  packages/superset-ui-core/src/query/processExtraFormData.ts
  packages/superset-ui-core/src/query/types/Query.ts
  packages/superset-ui-core/src/query/types/QueryFormData.ts
  packages/superset-ui-core/test/query/buildQueryContext.test.ts
  packages/superset-ui-core/test/query/buildQueryObject.test.ts
  packages/superset-ui-core/test/query/processExtraFormData.test.ts
  plugins/plugin-chart-echarts/src/BoxPlot/EchartsBoxPlot.tsx
  plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
  plugins/plugin-chart-echarts/src/BoxPlot/index.ts
  plugins/plugin-chart-echarts/src/Pie/EchartsPie.tsx
  plugins/plugin-chart-echarts/src/Pie/index.ts
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/index.ts
Labels: size/L

#1059 fix: Adding codecov script locally
  .github/workflows/ci.yml
  .github/workflows/codecov.sh
Labels: size/XXL

#1063 chore(plugin-chart-echarts): add time section for gauge chart
  plugins/plugin-chart-echarts/src/Gauge/controlPanel.tsx
Labels: size/XS

#1064 feat(table): groupby filter
  plugins/plugin-chart-table/src/buildQuery.ts
Labels: size/XS

#1065 chore: update documentation
  docs/debugging.md
Labels: size/XS

#1066 feat: add tooltip for full metric names
  packages/superset-ui-chart-controls/src/components/MetricOption.tsx
  packages/superset-ui-chart-controls/test/components/MetricOption.test.tsx
Labels: size/XS

#1067 fix: update yarn.lock
  yarn.lock
Labels: size/M

#1062 chore(plugin-chart-echarts): bump echarts to 5.1.0
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  yarn.lock
Labels: size/M

#1071 fix(plugin-chart-echarts): remove label line if below threshold
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
Labels: size/XS

#1072 fix(native-filters): support group by feature for server side pagination in table
  plugins/plugin-chart-table/src/buildQuery.ts
Labels: size/S

#1074 chore(plugin-chart-echarts): bump echarts 5.1.1
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  yarn.lock
Labels: size/S

#1073 chore: adds Emotion's CacheProvider and createCache as exports from Core package
  packages/superset-ui-core/package.json
  packages/superset-ui-core/src/style/index.ts
Labels: size/S

#1078 feat(plugin-chart-table): disable show_totals by default
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/XS

#1080 fix: further dialing-in of Emotion imports/exports
  packages/superset-ui-core/src/style/index.ts
Labels: size/S

#1082 fix(plugin-chart-table): resize and totals formatting bug
  packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/constants.tsx
  plugins/plugin-chart-table/src/DataTable/DataTable.tsx
  plugins/plugin-chart-table/src/DataTable/types/react-table.d.ts
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/i18n.ts
  plugins/plugin-chart-table/src/transformProps.ts
  plugins/plugin-chart-table/src/types.ts
  plugins/plugin-chart-table/src/utils/formatValue.ts
Labels: size/L
