Repository apache-superset/superset-ui, pull requests merged in 2021-03, with the labels that each got.

#959 feat(self-trigger): add backend pagination for the table
  packages/superset-ui-core/src/chart/models/ChartProps.ts
  packages/superset-ui-core/src/chart/types/Base.ts
  packages/superset-ui-core/src/query/buildQueryObject.ts
  packages/superset-ui-core/src/query/types/QueryFormData.ts
  plugins/plugin-chart-table/src/DataTable/DataTable.tsx
  plugins/plugin-chart-table/src/DataTable/components/ServerPagination.tsx
  plugins/plugin-chart-table/src/DataTable/utils/externalAPIs.ts
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/src/controlPanel.tsx
  plugins/plugin-chart-table/src/i18n.ts
  plugins/plugin-chart-table/src/transformProps.ts
  plugins/plugin-chart-table/src/types.ts
Labels: size/L

#978 feat: implement drag and drop filters controls
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-chart-controls/src/types.ts
Labels: size/S

#980 refactor(SupersetClient): use new /api/v1/security/csrf_token/ endpoint
  packages/superset-ui-core/src/connection/SupersetClientClass.ts
  packages/superset-ui-core/test/chart/clients/ChartClient.test.ts
  packages/superset-ui-core/test/chart/fixtures/constants.ts
  packages/superset-ui-core/test/connection/SupersetClient.test.ts
  packages/superset-ui-core/test/connection/SupersetClientClass.test.ts
  packages/superset-ui-core/test/connection/callApi/callApi.test.ts
  packages/superset-ui-core/test/connection/callApi/callApiAndParseWithTimeout.test.ts
  packages/superset-ui-core/test/connection/callApi/parseResponse.test.ts
  packages/superset-ui-core/test/connection/fixtures/constants.ts
  packages/superset-ui-core/test/query/api/setupClientForTest.ts
Labels: size/M

#988 fix: rename DnD types to match component names in Superset
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/types.ts
Labels: size/XS

#989 feat: responsive heatmap
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-heatmap/Stories.tsx
  plugins/legacy-plugin-chart-heatmap/src/Heatmap.css
  plugins/legacy-plugin-chart-heatmap/src/Heatmap.js
Labels: size/L

#977 feat: change font size on responsive for sankey and sunburst chart
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-sankey/Stories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/legacy-plugin-chart-sunburst/Stories.tsx
  plugins/legacy-plugin-chart-sankey/src/ReactSankey.jsx
  plugins/legacy-plugin-chart-sankey/src/Sankey.js
  plugins/legacy-plugin-chart-sankey/src/tests/utils.test.js
  plugins/legacy-plugin-chart-sankey/src/transformProps.js
  plugins/legacy-plugin-chart-sankey/src/utils.ts
  plugins/legacy-plugin-chart-sunburst/src/Sunburst.css
  plugins/legacy-plugin-chart-sunburst/src/Sunburst.js
Labels: size/L

#994 fix(plugin-chart-table): ignore duplicate percent metrics
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/src/index.ts
  plugins/plugin-chart-table/test/buildQuery.test.ts
Labels: size/M

#992 feat(core): add extra form data fields for native filters
  packages/superset-ui-core/src/query/buildQueryObject.ts
  packages/superset-ui-core/src/query/extractExtras.ts
  packages/superset-ui-core/src/query/processExtraFormData.ts
  packages/superset-ui-core/src/query/processFilters.ts
  packages/superset-ui-core/src/query/types/Query.ts
  packages/superset-ui-core/test/query/buildQueryObject.test.ts
  packages/superset-ui-core/test/query/extractExtras.test.ts
  packages/superset-ui-core/test/query/processExtraFormData.test.ts
Labels: size/L

#991 fix(plugin-chart-echarts): fix GraphViz crash when DnD FF enable
  plugins/plugin-chart-echarts/src/Graph/controlPanel.tsx
Labels: size/M

#1001 fix: show question mark icon when can not infer datatype
  packages/superset-ui-chart-controls/src/components/ColumnTypeLabel.tsx
Labels: size/XS

#998 refactor(chart-controls): optimize typing
  packages/superset-ui-chart-controls/src/types.ts
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/S

#1004 feat: implement Metrics dnd
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-chart-controls/src/types.ts
Labels: size/M

#1005 fix(plugin-chart-table): metrics should be undefined
  plugins/plugin-chart-table/src/buildQuery.ts
  plugins/plugin-chart-table/test/buildQuery.test.ts
Labels: size/S

#1007 fix(table): Fix backend pagination table case
  plugins/plugin-chart-table/src/DataTable/DataTable.tsx
Labels: size/XS

#973 feat(plugin-chart-echarts): add label date format for piechart and boxplot
  plugins/plugin-chart-echarts/src/BoxPlot/controlPanel.ts
  plugins/plugin-chart-echarts/src/BoxPlot/index.ts
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/BoxPlot/types.ts
  plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Pie/index.ts
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/Pie/types.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
Labels: size/L

#981 chore: translation strings in histogram
  plugins/legacy-plugin-chart-histogram/src/Histogram.jsx
Labels: ready-to-merge, size/XS

#1011 feat: support warning_markdown on metrics
  packages/superset-ui-chart-controls/src/components/MetricOption.tsx
  packages/superset-ui-core/package.json
  packages/superset-ui-core/src/components/SafeMarkdown.tsx
  packages/superset-ui-core/src/components/index.ts
  packages/superset-ui-core/src/index.ts
  packages/superset-ui-core/src/query/types/Metric.ts
  yarn.lock
Labels: size/L

#1012 fix: time formatter test
  packages/superset-ui-core/test/time-format/factories/createD3TimeFormatter.test.ts
Labels: size/XS

#1000 feat: add syria to Country Maps
  plugins/legacy-plugin-chart-country-map/src/countries.js
  plugins/legacy-plugin-chart-country-map/src/countries/syria.geojson
Labels: size/M

#1010 feat(plugin-chart-echarts): Emit cross filters for pie and boxplot
  plugins/plugin-chart-echarts/src/BoxPlot/EchartsBoxPlot.tsx
  plugins/plugin-chart-echarts/src/BoxPlot/controlPanel.ts
  plugins/plugin-chart-echarts/src/BoxPlot/index.ts
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/BoxPlot/types.ts
  plugins/plugin-chart-echarts/src/Pie/EchartsPie.tsx
  plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Pie/index.ts
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/Pie/types.ts
  plugins/plugin-chart-echarts/src/components/Echart.tsx
  plugins/plugin-chart-echarts/src/types.ts
Labels: needs-more-info, size/L

#1014 fix(plugin-chart-echarts): fill missing values when stacked chart
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
  plugins/plugin-chart-echarts/test/index.test.ts
  plugins/plugin-chart-echarts/test/utils/series.test.ts
Labels: size/M

#1020 fix: incorporating ScheduleQueries into featureFlags
  packages/superset-ui-core/src/utils/featureFlags.ts
Labels: size/S

#1013 fix(generator-superset): update plugin template to 0.17 standards
  packages/generator-superset/generators/plugin-chart/templates/package.erb
  packages/generator-superset/generators/plugin-chart/templates/src/plugin/buildQuery.erb
  packages/generator-superset/generators/plugin-chart/templates/src/plugin/controlPanel.erb
Labels: size/M

#1025 fix(legacy-plugin-chart-country-map): Add Syria to control panel selection
  plugins/legacy-plugin-chart-country-map/src/controlPanel.ts
Labels: size/XS

#1033 feat: add default series_limit
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
Labels: size/XS

#1028 feat(plugin-chart-table): add small number formatter
  packages/superset-ui-chart-controls/src/components/InfoTooltipWithTrigger.tsx
  packages/superset-ui-chart-controls/src/components/Select.tsx
  packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/constants.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/TableStories.tsx
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-table/testData.ts
  plugins/plugin-chart-table/src/TableChart.tsx
  plugins/plugin-chart-table/src/utils/DateWithFormatter.ts
  plugins/plugin-chart-table/src/utils/formatValue.ts
Labels: size/L
