Repository apache-superset/superset-ui, pull requests merged in 2021-05, with the labels that each got.

#1084 feat(plugin-chart-graph): add node/edge size and edge symbol control
  plugins/plugin-chart-echarts/src/Graph/constants.ts
  plugins/plugin-chart-echarts/src/Graph/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Graph/transformProps.ts
  plugins/plugin-chart-echarts/src/Graph/types.ts
  plugins/plugin-chart-echarts/test/Graph/transformProps.test.ts
Labels: size/L

#1056 fix(plugin-chart-echarts): include label length in distance calculation
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Gauge/constants.ts
  plugins/plugin-chart-echarts/src/Gauge/transformProps.ts
Labels: size/S

#1085 fix(plugin-chart-table): hide column configs when no columns
  packages/superset-ui-chart-controls/src/shared-controls/components/ColumnConfigControl/ColumnConfigControl.tsx
Labels: size/XS

#1089 feat(plugin-chart-pivot-table): implement barchart highlight
  plugins/plugin-chart-pivot-table/package.json
  plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
Labels: size/XS

#1092 fix(legacy-plugin-chart-sankey): ensure tooltip position is within chart
  plugins/legacy-plugin-chart-sankey/src/Sankey.js
Labels: size/XS

#1095 fix(plugin-chart-table): check if control values are set
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/XS

#1096 fix: avoid unnecessary requeries caused by ownState
  plugins/plugin-chart-echarts/src/BoxPlot/EchartsBoxPlot.tsx
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/BoxPlot/types.ts
  plugins/plugin-chart-echarts/src/Funnel/EchartsFunnel.tsx
  plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
  plugins/plugin-chart-echarts/src/Pie/EchartsPie.tsx
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/Radar/EchartsRadar.tsx
  plugins/plugin-chart-echarts/src/Radar/transformProps.ts
  plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
Labels: size/M

#1097 feat(plugin-chart-echarts): hide/show dependent controls
  plugins/plugin-chart-echarts/src/Funnel/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Graph/controlPanel.tsx
  plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Radar/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/controls.tsx
Labels: size/L

#1102 feat(core): clean up datatype logic
  packages/superset-ui-chart-controls/src/components/ColumnOption.tsx
  packages/superset-ui-chart-controls/src/components/ColumnTypeLabel.tsx
  packages/superset-ui-chart-controls/src/constants.ts
  packages/superset-ui-chart-controls/src/types.ts
  packages/superset-ui-chart-controls/test/components/ColumnOption.test.tsx
  packages/superset-ui-chart-controls/test/components/ColumnTypeLabel.test.tsx
  packages/superset-ui-core/src/query/types/Column.ts
  packages/superset-ui-core/test/fixtures.ts
  packages/superset-ui-core/test/query/getMetricLabel.test.ts
Labels: size/L

#1103 feat(plugin-chart-echarts): Enhancements of treemap tooltip
  plugins/plugin-chart-echarts/src/Treemap/index.ts
  plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
  plugins/plugin-chart-echarts/src/Treemap/types.ts
Labels: size/M

#1108 chore: removes react-bootstrap
  package.json
  packages/superset-ui-chart-controls/package.json
  packages/superset-ui-chart-controls/src/components/CertifiedIconWithTooltip.tsx
  packages/superset-ui-core/package.json
  packages/superset-ui-demo/package.json
  yarn.lock
Labels: size/L

#1111 feat(plugin-chart-echarts): set up orderby by default on Pie chart
  plugins/plugin-chart-echarts/src/Pie/controlPanel.tsx
Labels: size/XS

#1110 fix(plugin-chart-echarts): funnel chart improvements
  plugins/plugin-chart-echarts/src/Funnel/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
Labels: size/M

#1109 fix(plugin-chart-echarts): disabling dragging the treemap on the dashboard
  packages/superset-ui-demo/storybook/stories/plugins/plugin-chart-echarts/Treemap/Stories.tsx
  plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
  plugins/plugin-chart-echarts/src/Treemap/types.ts
Labels: size/S

#1113 feat(plugin-chart-echarts): SORT BY METRIC add checkbox to Gauge
  plugins/plugin-chart-echarts/src/Gauge/buildQuery.ts
  plugins/plugin-chart-echarts/src/Gauge/controlPanel.tsx
Labels: size/S

#1116 fix: fixes metric control when changing viz type to tree chart
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
Labels: size/XS

#1121 feat(core): add support for empty results and refresh indicator
  packages/superset-ui-core/src/chart/components/SuperChart.tsx
  packages/superset-ui-core/src/chart/models/ChartMetadata.ts
  packages/superset-ui-core/src/chart/models/ChartProps.ts
  packages/superset-ui-core/test/chart/models/ChartProps.test.ts
Labels: size/M

#1122 feat(core): add orderyby shared control
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
Labels: size/XS

#1112 feat(plugin-chart-echarts): add orderby on Radar chart
  plugins/plugin-chart-echarts/src/Radar/buildQuery.ts
  plugins/plugin-chart-echarts/src/Radar/controlPanel.tsx
Labels: size/M

#1129 feat(core): add support for case insensitive LIKE operator
  packages/superset-ui-core/src/query/types/Operator.ts
Labels: size/XS

#1127 feat(chart-controls): implement drag&drop controls for all charts
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-chart-controls/src/utils/columnChoices.ts
  plugins/legacy-plugin-chart-heatmap/src/controlPanel.ts
  plugins/legacy-plugin-chart-histogram/src/controlPanel.ts
  plugins/legacy-plugin-chart-map-box/src/controlPanel.ts
  plugins/legacy-preset-chart-nvd3/src/Bubble/controlPanel.ts
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/L

#1125 feat(plugin-chart-echarts): Treemap improvements
  plugins/plugin-chart-echarts/src/Treemap/buildQuery.ts
  plugins/plugin-chart-echarts/src/Treemap/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
  plugins/plugin-chart-echarts/src/Treemap/types.ts
  plugins/plugin-chart-echarts/test/Treemap/transformProps.test.ts
Labels: size/L

#1132 fix(plugin-chart-pivot-table): fix displaying column names when labels are available
  plugins/plugin-chart-pivot-table/package.json
  plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
  plugins/plugin-chart-pivot-table/src/plugin/transformProps.ts
  plugins/plugin-chart-pivot-table/src/types.ts
  plugins/plugin-chart-pivot-table/test/plugin/transformProps.test.ts
Labels: size/S

#1133 feat(core): add new feature flags
  packages/superset-ui-core/src/utils/featureFlags.ts
Labels: size/XS

#1114 feat(core): remove defaults for time range filter and Metrics
  packages/superset-ui-chart-controls/src/shared-controls/dndControls.tsx
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/M

#1115 feat(plugin-chart-echarts): add x-filtering to treemap
  plugins/plugin-chart-echarts/src/Treemap/EchartsTreemap.tsx
  plugins/plugin-chart-echarts/src/Treemap/constants.ts
  plugins/plugin-chart-echarts/src/Treemap/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Treemap/index.ts
  plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
  plugins/plugin-chart-echarts/src/Treemap/types.ts
Labels: size/L
