Repository apache-superset/superset-ui, pull requests merged in 2021-10, with the labels that each got.

#1381 feat(legacy-plugin-chart-histogram): cumulative histogram option
  plugins/legacy-plugin-chart-histogram/src/Histogram.jsx
  plugins/legacy-plugin-chart-histogram/src/controlPanel.ts
  plugins/legacy-plugin-chart-histogram/src/transformProps.js
Labels: size/S

#1384 fix: replace absolute difference with difference in legacy charts
  plugins/legacy-plugin-chart-partition/src/controlPanel.tsx
  plugins/legacy-plugin-chart-rose/src/controlPanel.tsx
  plugins/legacy-preset-chart-nvd3/src/NVD3Controls.tsx
Labels: size/S

#1383 fix: replace absolute difference with difference in echart
  packages/superset-ui-chart-controls/src/sections/advancedAnalytics.tsx
  packages/superset-ui-chart-controls/test/utils/operators/rollingWindowOperator.test.ts
  packages/superset-ui-chart-controls/test/utils/operators/timeCompareOperator.test.ts
  packages/superset-ui-core/src/query/types/AdvancedAnalytics.ts
Labels: size/S

#1388 feat(native-filters): add feature flag ENABLE_FILTER_BOX_MIGRATION
  packages/superset-ui-core/src/utils/featureFlags.ts
Labels: size/XS

#1389 feat(plugin-chart-echarts): add support for custom forecasts
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/utils/prophet.ts
  plugins/plugin-chart-echarts/test/utils/prophet.test.ts
Labels: size/M

#1386 fix: rolling and cum operator in multiple series chart
  packages/superset-ui-chart-controls/src/operators/rollingWindowOperator.ts
  packages/superset-ui-chart-controls/test/utils/operators/rollingWindowOperator.test.ts
  packages/superset-ui-core/src/query/types/PostProcessing.ts
  plugins/plugin-chart-echarts/src/Timeseries/buildQuery.ts
Labels: size/M

#1392 chore: hide rolling_periods and min_periods
  packages/superset-ui-chart-controls/src/sections/advancedAnalytics.tsx
Labels: size/XS
