Repository apache-superset/superset-ui, pull requests merged in 2021-07, with the labels that each got.

#1126 fix(plugin-chart-echarts): sanitize series from html tags
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
  plugins/plugin-chart-echarts/src/Graph/transformProps.ts
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/utils/prophet.ts
  plugins/plugin-chart-echarts/src/utils/series.ts
  plugins/plugin-chart-echarts/test/utils/series.test.ts
Labels: size/M

#1200 fix(plugin-chart-echarts): enable animation to clear old nodes
  plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
Labels: size/XS

#1201 chore: tweaking plugin metadata again
  plugins/legacy-preset-chart-big-number/src/BigNumber/index.ts
  plugins/legacy-preset-chart-nvd3/src/TimePivot/index.js
Labels: size/XS

#1202 chore: add/edit plugin descriptions
  plugins/legacy-plugin-chart-pivot-table/src/index.js
  plugins/legacy-plugin-chart-time-table/src/index.ts
  plugins/legacy-preset-chart-nvd3/src/Compare/index.js
  plugins/legacy-preset-chart-nvd3/src/LineMulti/index.js
  plugins/plugin-chart-echarts/src/Radar/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/index.ts
Labels: size/S

#1161 fix(plugin-chart-echarts): fix time-series chart xAxisShowMin(Max)Label default value
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
Labels: size/M

#1016 feat(plugin-chart-echarts): Add cross filter for timeseries
  docs/debugging.md
  plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/index.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
Labels: size/L

#1206 feat: Normalize orderby clause
  packages/superset-ui-core/src/query/index.ts
  packages/superset-ui-core/src/query/normalizeOrderBy.ts
  packages/superset-ui-core/test/query/normalizeOrderBy.test.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/buildQuery.ts
Labels: ready-for-review, size/L

#1205 feat(plugin-chart-echarts): x-filtering improvement in radar chart
  plugins/plugin-chart-echarts/src/Radar/EchartsRadar.tsx
  plugins/plugin-chart-echarts/src/Radar/transformProps.ts
  plugins/plugin-chart-echarts/src/Treemap/constants.ts
  plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
  plugins/plugin-chart-echarts/src/constants.ts
Labels: size/S

#1208 fix: remove console.log from timeseries chart
  plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
Labels: size/XS

#1203 feat(plugin-chart-echarts): add x-filtering in gauge chart
  plugins/plugin-chart-echarts/src/Gauge/EchartsGauge.tsx
  plugins/plugin-chart-echarts/src/Gauge/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Gauge/index.ts
  plugins/plugin-chart-echarts/src/Gauge/transformProps.ts
  plugins/plugin-chart-echarts/src/Gauge/types.ts
  plugins/plugin-chart-echarts/src/types.ts
Labels: size/L

#1204 feat(plugin-chart-echarts): single select by default for pie chart
  plugins/plugin-chart-echarts/src/Pie/EchartsPie.tsx
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
Labels: size/XS

#1212 fix(plugin-chart-echarts): single select in boxPlot x-filtering
  plugins/plugin-chart-echarts/src/BoxPlot/EchartsBoxPlot.tsx
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
Labels: size/XS

#1211 feat(plugin-chart-echarts): crossfilter with single selection in the funnel chart
  plugins/plugin-chart-echarts/src/Funnel/EchartsFunnel.tsx
  plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
Labels: size/XS

#1215 feat(chart-controls): implement color formatters utils
  packages/superset-ui-chart-controls/src/types.ts
  packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts
  packages/superset-ui-chart-controls/src/utils/index.ts
  packages/superset-ui-chart-controls/test/utils/getColorFormatters.test.ts
Labels: size/L

#1217 feat(plugin-chart-pivot-table): column, date and conditional formatting
  plugins/plugin-chart-pivot-table/package.json
  plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
  plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
  plugins/plugin-chart-pivot-table/src/plugin/index.ts
  plugins/plugin-chart-pivot-table/src/plugin/transformProps.ts
  plugins/plugin-chart-pivot-table/src/types.ts
  plugins/plugin-chart-pivot-table/test/plugin/buildQuery.test.ts
  plugins/plugin-chart-pivot-table/test/plugin/transformProps.test.ts
  yarn.lock
Labels: pivot-table

#1235 chore: three charts to the correct tags
  plugins/legacy-plugin-chart-heatmap/src/index.js
  plugins/legacy-plugin-chart-map-box/src/index.js
  plugins/plugin-chart-word-cloud/src/plugin/index.ts
Labels: size/S

#1171 chore(chart-controls): improve typing for mapStateToProps
  packages/superset-ui-chart-controls/src/types.ts
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/XS

#1236 chore: add tags and description metadata
  plugins/legacy-plugin-chart-country-map/src/index.js
  plugins/legacy-plugin-chart-paired-t-test/src/index.js
  plugins/legacy-plugin-chart-parallel-coordinates/src/index.js
  plugins/legacy-plugin-chart-rose/src/index.js
  plugins/legacy-plugin-chart-time-table/src/index.ts
  plugins/legacy-preset-chart-big-number/src/BigNumber/index.ts
  plugins/legacy-preset-chart-big-number/src/BigNumberTotal/index.ts
  plugins/legacy-preset-chart-nvd3/src/Compare/index.js
  plugins/legacy-preset-chart-nvd3/src/LineMulti/index.js
  plugins/plugin-chart-echarts/src/MixedTimeseries/index.ts
  plugins/plugin-chart-table/src/index.ts
Labels: size/M

#1239 fix(plugin-chart-echarts): make filtered pie slices semi-transparent
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
Labels: size/XS

#1241 chore: add translation for description
  packages/superset-ui-chart-controls/src/sections.tsx
  packages/superset-ui-chart-controls/src/utils/D3Formatting.ts
  plugins/legacy-plugin-chart-country-map/src/controlPanel.ts
  plugins/legacy-plugin-chart-paired-t-test/src/index.js
  plugins/legacy-plugin-chart-parallel-coordinates/src/index.js
  plugins/plugin-chart-echarts/src/Gauge/controlPanel.tsx
  plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
Labels: size/S

#1240 feat(plugin-chart-pivot-table): sort by metric
  plugins/plugin-chart-pivot-table/src/plugin/buildQuery.ts
  plugins/plugin-chart-pivot-table/src/plugin/controlPanel.ts
  plugins/plugin-chart-pivot-table/src/types.ts
  plugins/plugin-chart-pivot-table/test/plugin/buildQuery.test.ts
  plugins/plugin-chart-pivot-table/test/plugin/transformProps.test.ts
Labels: size/M

#1242 chore(core): move emotion deps to peer deps
  packages/superset-ui-core/package.json
  packages/superset-ui-demo/package.json
Labels: size/XS

#1244 feat(plugin-chart-echarts): implement x-filter opacity in ts chart
  plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
Labels: size/M

#1245 chore: only keey Distribution category
  plugins/legacy-plugin-chart-sankey/src/index.js
  plugins/legacy-plugin-chart-treemap/src/index.js
  plugins/legacy-preset-chart-nvd3/src/DistBar/index.js
Labels: size/S

#1246 chore: add feature flag
  packages/superset-ui-core/src/utils/featureFlags.ts
Labels: size/XS

#1243 feat(plugin-chart-pivot-table): add sort by result to data pane
  plugins/plugin-chart-pivot-table/src/plugin/buildQuery.ts
Labels: size/S

#1251 fix: add feature flags for pagination control in table chart
  plugins/plugin-chart-table/src/controlPanel.tsx
Labels: size/S

#1250 chore: remove V2 and add Deprecated
  plugins/legacy-plugin-chart-pivot-table/src/index.js
  plugins/legacy-plugin-chart-treemap/src/index.js
  plugins/plugin-chart-echarts/src/Treemap/index.ts
  plugins/plugin-chart-pivot-table/src/plugin/index.ts
Labels: rush!, size/XS

#1253 chore: Revert "chore: remove V2 and add Deprecated"
  plugins/legacy-plugin-chart-pivot-table/src/index.js
  plugins/legacy-plugin-chart-treemap/src/index.js
  plugins/plugin-chart-echarts/src/Treemap/index.ts
  plugins/plugin-chart-pivot-table/src/plugin/index.ts
Labels: size/XS
