Repository apache-superset/superset-ui, pull requests merged in 2021-09, with the labels that each got.

#1334 feat(legacy-plugin-chart-country-map): add Vietnam map
  plugins/legacy-plugin-chart-country-map/src/countries.ts
  plugins/legacy-plugin-chart-country-map/src/countries/vietnam.geojson
Labels: size/M

#1307 fix: bignumber format by time formatter
  plugins/legacy-preset-chart-big-number/src/BigNumber/BigNumber.tsx
  plugins/legacy-preset-chart-big-number/src/BigNumber/transformProps.ts
  plugins/legacy-preset-chart-big-number/src/BigNumberTotal/controlPanel.ts
  plugins/legacy-preset-chart-big-number/test/transformProps.test.ts
Labels: size/M

#1326 fix(plugin-chart-echarts): [gauge chart] filter indicator not be shown
  plugins/plugin-chart-echarts/src/Gauge/index.ts
Labels: size/XS

#1337 fix(plugin-chart-echarts): [feature-parity] display custom metric label
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/utils/prophet.ts
Labels: size/S

#1340 chore(plugin-chart-echarts): bump to ECharts 5.2.0
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Gauge/transformProps.ts
Labels: size/XS

#1347 chore(core): move @emotion/styled to peer dependency
  packages/superset-ui-chart-controls/package.json
  packages/superset-ui-core/package.json
  packages/superset-ui-demo/package.json
  yarn.lock
Labels: size/M

#1344 fix(legacy-plugin-chart-country-map): Correct ISO 3166-2 county codes for Estonia
  plugins/legacy-plugin-chart-country-map/src/countries/estonia.geojson
Labels: size/S

#1339 chore: isolate the one actual jquery dependency
  plugins/legacy-plugin-chart-pivot-table/package.json
  plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
Labels: size/XS

#1355 chore: Revert "chore: isolate the one actual jquery dependency"
  plugins/legacy-plugin-chart-pivot-table/package.json
  plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
Labels: size/XS

#1351 feat(plugin-chart-echarts): add x and y label support for 9 charts
  packages/superset-ui-chart-controls/src/sections/chartTitle.tsx
  packages/superset-ui-chart-controls/src/sections/index.ts
  plugins/plugin-chart-echarts/src/BoxPlot/controlPanel.ts
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/BoxPlot/types.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/types.ts
  plugins/plugin-chart-echarts/src/Timeseries/Area/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Regular/Scatter/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Regular/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/Step/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/controlPanel.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/Timeseries/types.ts
  plugins/plugin-chart-echarts/src/types.ts
  plugins/plugin-chart-pivot-table/README.md
Labels: size/L

#1352 chore: clean up mixed-timeseries chart
  plugins/plugin-chart-echarts/src/MixedTimeseries/buildQuery.ts
Labels: size/M

#1356 feat(core): add support for non-temporal series limit
  packages/superset-ui-chart-controls/src/shared-controls/index.tsx
  packages/superset-ui-core/src/query/buildQueryObject.ts
  packages/superset-ui-core/src/query/types/Query.ts
  packages/superset-ui-core/src/query/types/QueryFormData.ts
  plugins/plugin-chart-echarts/src/BoxPlot/buildQuery.ts
  plugins/plugin-chart-echarts/src/BoxPlot/controlPanel.ts
  plugins/plugin-chart-echarts/test/BoxPlot/buildQuery.test.ts
Labels: size/M

#1362 chore: replace mathjs with mexp
  plugins/legacy-preset-chart-nvd3/package.json
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/utils/annotation.ts
  plugins/plugin-chart-echarts/test/utils/annotation.test.ts
  yarn.lock
Labels: size/L

#1363 chore: do prettier for yaml file
  .github/dependabot.yml
Labels: size/L

#1370 chore(plugin-chart-echarts): bump to ECharts 5.2.1
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/BoxPlot/transformProps.ts
  plugins/plugin-chart-echarts/src/BoxPlot/types.ts
  plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
  plugins/plugin-chart-echarts/src/Funnel/types.ts
  plugins/plugin-chart-echarts/src/Gauge/transformProps.ts
  plugins/plugin-chart-echarts/src/Graph/transformProps.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/MixedTimeseries/types.ts
  plugins/plugin-chart-echarts/src/Pie/transformProps.ts
  plugins/plugin-chart-echarts/src/Pie/types.ts
  plugins/plugin-chart-echarts/src/Radar/transformProps.ts
  plugins/plugin-chart-echarts/src/Radar/types.ts
  plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/Tree/transformProps.ts
  plugins/plugin-chart-echarts/src/Treemap/transformProps.ts
  plugins/plugin-chart-echarts/src/Treemap/types.ts
  plugins/plugin-chart-echarts/src/types.ts
  yarn.lock
Labels: size/L

#1360 fix: Pivot table now at 100% width
  plugins/legacy-plugin-chart-pivot-table/src/PivotTable.js
  plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx
  plugins/plugin-chart-pivot-table/src/types.ts
Labels: size/XS

#1371 refactor(core): move mexp from plugins to core
  packages/superset-ui-core/package.json
  packages/superset-ui-core/src/index.ts
  packages/superset-ui-core/src/math-expression/index.ts
  packages/superset-ui-core/test/math-expression/index.test.ts
  plugins/legacy-preset-chart-nvd3/package.json
  plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
  plugins/plugin-chart-echarts/package.json
  plugins/plugin-chart-echarts/src/Timeseries/transformers.ts
  plugins/plugin-chart-echarts/src/utils/annotation.ts
Labels: size/L

#1375 chore: Remove immutable.js from map-box
  plugins/legacy-plugin-chart-map-box/package.json
  plugins/legacy-plugin-chart-map-box/src/MapBox.jsx
  plugins/legacy-plugin-chart-map-box/src/ScatterPlotGlowOverlay.jsx
  yarn.lock
Labels: size/M

#1374 chore: upgrade to Node 16
  .github/workflows/ci.yml
  .github/workflows/release.yml
  package.json
Labels: size/XS

#1377 feat: add y-axis control to bubble chart
  plugins/legacy-preset-chart-nvd3/src/Bubble/controlPanel.ts
Labels: size/XS

#1324 feat(plugin-chart-echarts): [feature-parity] support double clicking legend and series to view single selected series
  plugins/plugin-chart-echarts/src/Timeseries/EchartsTimeseries.tsx
  plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts
  plugins/plugin-chart-echarts/src/components/Echart.tsx
  plugins/plugin-chart-echarts/src/types.ts
Labels: size/L

#1319 feat: added italian regions country map
  plugins/legacy-plugin-chart-country-map/src/countries.ts
  plugins/legacy-plugin-chart-country-map/src/countries/italy_regions.geojson
Labels: size/M, needs-more-info
